(function(){
'use strict';
var KEY='rural_pastagem_confinamento_v1';
var CAPACITY=25600;
var MONTHS=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
var TITLES={overview:'Visão Geral',capacity:'Capacidade e Movimentação',active:'Lotes Ativos',pens:'Mapa dos Currais',analysis:'Painel de Análise',rural:'Bois Próprios',toreton:'Compra de Toreton',hotel:'Hotelaria',cash:'Fluxo de Caixa',plans:'Planos Confirmados'};
var state=loadState();
var reportSort={key:'line',dir:1};
var cashSelectedMonths=null;
var penSelected=new Set(), penDetailKey='';

function defaultPenBlocks(){return [{id:'01',name:'Bloco 01',lines:['A','B','C','D','E','F']},{id:'02',name:'Bloco 02',lines:['G','H','I','J','K']},{id:'03',name:'Bloco 03',lines:['L','M','N','O','P']}];}
function normalizedPenBlocks(saved){var standard=defaultPenBlocks();if(!Array.isArray(saved)||saved.length!==3)return standard;return standard.map(function(block,i){return {id:block.id,name:String((saved[i]||{}).name||block.name),lines:block.lines.slice()};});}
function defaults(){return {version:1,year:2027,horizonMonths:12,capacity:CAPACITY,capacityByMonth:{},penBlocks:defaultPenBlocks(),defaults:{sale:1500,buy:1100,hotel:350},cash:{paymentDays:0,anticipate:false,annualInterest:6.5},lots:[],notes:[],shipmentPlans:[],hasConsumo:true,plans:[],activePlanId:null,updatedAt:new Date().toISOString()};}
function loadState(){try{var d=JSON.parse(localStorage.getItem(KEY));if(d&&Array.isArray(d.lots)){var base=defaults();return Object.assign(base,d,{horizonMonths:Number(d.horizonMonths)===24?24:12,capacity:num(d.capacity)||CAPACITY,capacityByMonth:d.capacityByMonth||{},penBlocks:normalizedPenBlocks(d.penBlocks),defaults:Object.assign(base.defaults,d.defaults||{}),cash:Object.assign(base.cash,d.cash||{}),notes:Array.isArray(d.notes)?d.notes:[],shipmentPlans:Array.isArray(d.shipmentPlans)?d.shipmentPlans:[],hasConsumo:d.hasConsumo!==false});}}catch(e){}return defaults();}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));}
function el(id){return document.getElementById(id);}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function num(v){v=Number(v);return isFinite(v)?v:0;}
function int(v){return Math.round(num(v)).toLocaleString('pt-BR');}
function usd(v){return 'US$ '+Math.round(num(v)).toLocaleString('pt-BR');}
function uid(prefix){return (prefix||'id')+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);}
function keyOf(y,m){return String(y)+'-'+String(m+1).padStart(2,'0');}
function addMonths(key,n){var p=String(key).split('-'),d=new Date(Number(p[0]),Number(p[1])-1+n,1);return keyOf(d.getFullYear(),d.getMonth());}
function labelKey(key){if(!key)return '—';var p=key.split('-');return MONTHS[Number(p[1])-1]+'/'+p[0].slice(2);}
function planningStartKey(){var d=new Date();return keyOf(d.getFullYear(),d.getMonth());}
function horizonMonths(){return Number(state.horizonMonths)===24?24:12;}
function monthKeys(){var start=planningStartKey();return Array.from({length:horizonMonths()},function(_,i){return addMonths(start,i);});}
function updateHorizonLabels(){var months=horizonMonths(),start=planningStartKey();el('planningWindow').textContent=labelKey(start)+' a '+labelKey(addMonths(start,months-1));el('horizonMonths').value=String(months);el('capacityHorizonTitle').textContent='Capacidade nos próximos '+months+' meses';['overviewRange','cashRange','capacityRange'].forEach(function(id){var select=el(id),current=Number(select.value)||4;Array.from(select.querySelectorAll('[data-long-range]')).forEach(function(o){o.remove();});if(months===24){[18,24].forEach(function(value){var option=document.createElement('option');option.value=String(value);option.textContent=value+' meses';option.dataset.longRange='1';select.appendChild(option);});}if(current>months)current=months;select.value=String(current);});}
function capacityFor(key){return Math.max(1,Math.round(num((state.capacityByMonth||{})[key])||num(state.capacity)||CAPACITY));}
function sum(a,fn){return a.reduce(function(s,x,i){return s+(fn?num(fn(x,i)):num(x));},0);}
function showToast(msg){var t=el('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(function(){t.classList.remove('show');},2600);}
function lotTypeLabel(t){return t==='rural'?'Rural':t==='toreton'?'Toreton':'Hotelaria';}
function normalizedCategory(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim().toUpperCase();}
function categoryIsOwn(value){var category=normalizedCategory(value);return category==='RIP'||category==='TORETON'||category==='COMPRAS';}
function entryTypeIsOwn(value){return /^ANIMAIS?\b/i.test(normalizedCategory(value));}
function activeReportDate(){var lots=state.lots.filter(function(l){return l.source==='feedmanager';});return lots.length?lots.map(function(l){return l.reportDate||'';}).sort().pop():'';}
function decimal(v,d){return Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});}
function numberBR(v){var x=parseFloat(String(v||'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));return isFinite(x)?x:0;}
function inputNumber(v){var s=String(v==null?'':v).trim();if(!s)return null;s=s.replace(/\s/g,'');if(s.indexOf(',')>=0)s=s.replace(/\./g,'').replace(',','.');var x=parseFloat(s.replace(/[^0-9.-]/g,''));return isFinite(x)?x:null;}
function lotKey(l){return normalizedCategory(l.name)+'|'+String(l.entryDate||'');}
function shipmentFor(l){var key=lotKey(l);return (state.shipmentPlans||[]).find(function(p){return p.lotKey===key;})||null;}
function deleteShipment(key){var before=(state.shipmentPlans||[]).length;state.shipmentPlans=(state.shipmentPlans||[]).filter(function(p){return p.lotKey!==key;});if(state.shipmentPlans.length===before)return;save();renderAll();if(!el('penDrawer').hidden)renderPenDetail();showToast('Embarque excluído. O lote foi mantido.');}
function parseShipmentDate(v){var s=String(v||'').trim(),m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m)return m[3]+'-'+m[2].padStart(2,'0')+'-'+m[1].padStart(2,'0');m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);return m?m[1]+'-'+m[2].padStart(2,'0')+'-'+m[3].padStart(2,'0'):'';}
function activeNotes(l){var lk=lotKey(l);return state.notes.filter(function(n){return n.status==='active'&&((n.scope==='lot'&&n.targetKey===lk)||(n.scope==='pen'&&n.targetKey===l.pen));});}
function addNote(e){e.preventDefault();var l=penDetailLot(),fd=new FormData(e.target),scope=fd.get('scope'),text=String(fd.get('text')||'').trim();if(!l||!text)return;state.notes.push({id:uid(),scope:scope,targetKey:scope==='lot'?lotKey(l):l.pen,lotName:l.name,pen:l.pen,text:text,status:'active',createdAt:new Date().toISOString(),closedAt:''});save();renderPens();renderPenDetail();showToast('Anotação salva.');}
function concludeNote(id){var n=state.notes.find(function(x){return x.id===id;});if(!n)return;n.status='closed';n.closedAt=new Date().toISOString();save();renderPens();renderPenDetail();showToast('Anotação concluída e mantida no histórico.');}
function closePenNotes(){var l=penDetailLot();if(!l)return;var list=state.notes.filter(function(n){return n.status==='active'&&n.scope==='pen'&&n.targetKey===l.pen;});if(!list.length){showToast('Este curral não possui anotação ativa.');return;}if(!confirm('Concluir as '+list.length+' anotações ativas deste curral? Elas continuarão no histórico.'))return;list.forEach(function(n){n.status='closed';n.closedAt=new Date().toISOString();});save();renderPens();renderPenDetail();showToast('Anotações do curral concluídas.');}
function noteCard(n){return '<article class="note-card '+(n.status==='closed'?'closed':'')+'">'+(n.status==='active'?'<button type="button" data-close-note="'+n.id+'">Concluir</button>':'')+'<small>'+(n.scope==='lot'?'LOTE':'CURRAL')+' · '+new Date(n.createdAt).toLocaleString('pt-BR')+(n.closedAt?' · concluída '+new Date(n.closedAt).toLocaleString('pt-BR'):'')+'</small><p>'+esc(n.text)+'</p></article>';}
function nearbyDiet(clean,y,isNew){var lo=isNew?338:340,hi=isNew?400:412;return clean.filter(function(i){var x=i.transform[4],dy=i.transform[5]-y,t=String(i.str||'').trim();return x>=lo&&x<hi&&dy>=-13&&dy<=13&&t&&!/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(t);}).sort(function(a,b){var dd=b.transform[5]-a.transform[5];return Math.abs(dd)>2?dd:a.transform[4]-b.transform[4];}).map(function(i){return String(i.str).trim();}).join(' ').trim();}
function reportColumns(hasConsumo){
  // A Bovino.OS mudou o relatório em set/2026: a coluna "Consumo MN total da baia" foi retirada,
  // o que deslocou (para a direita) todas as colunas seguintes (D. conf., D. trato, GMD, pesos, datas).
  return hasConsumo?{entryWeight:[412,441],entryDate:[443,486],days:[486,512],treatmentDays:[512,544],gmd:[544,572],estimatedWeight:[572,604],exitWeight:[604,631],estimatedExit:[632,680],consumption:[680,715],kgCabMS:[715,748],kgCabMN:[748,778],pv:[778,820]}
  :{entryWeight:[400,454],entryDate:[454,493],days:[493,535],treatmentDays:[535,565],gmd:[565,593],estimatedWeight:[593,623],exitWeight:[623,653],estimatedExit:[653,692],consumption:null,kgCabMS:[692,735],kgCabMN:[735,767],pv:[767,830]};
}
function daysSince(iso){if(!iso)return null;var d=new Date(iso+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);return Math.round((now-d)/86400000);}
function freshnessLabel(iso){var n=daysSince(iso);if(n===null)return '';var cls=n>=3?'stale':n>=1?'aging':'',text=n<=0?'hoje':n===1?'há 1 dia':'há '+n+' dias';return ' <b class="freshness '+cls+'">('+text+')</b>';}
function renderHeaderPosition(){var el2=el('positionLabel');if(!el2)return;var reportDate=activeReportDate();el2.innerHTML=reportDate?'Posição em '+esc(formatIsoDate(reportDate))+freshnessLabel(reportDate):'Nenhum relatório de lotes ativos importado';}

function ruralExitFromMonthKey(mk){var entryDate=mk+'-15',exitDate=addDaysToIso(entryDate,120);return {entryDate:entryDate,exitDate:exitDate,exit:exitDate.slice(0,7)};}
function normalizeFeedManagerLots(){
  var changed=false,next=[];
  state.lots.forEach(function(l){
    if(l.source==='planejamento'){var ex=ruralExitFromMonthKey(l.entry);if(l.exit!==ex.exit||l.entryDate!==ex.entryDate){l.exit=ex.exit;l.entryDate=ex.entryDate;l.exitDate=ex.exitDate;changed=true;}next.push(l);return;}
    if(l.source!=='feedmanager'){next.push(l);return;}
    if(l.entryDate){var calculatedExit=addDaysToIso(l.entryDate,120);if(calculatedExit&&l.exitDate!==calculatedExit){l.exitDate=calculatedExit;l.exit=calculatedExit.slice(0,7);changed=true;}}
    var rawType=normalizedCategory(l.rawEntryType),hasStandardType=/^(ANIMAIS?\b|BOITEL|PARCERIA)/.test(rawType),own=hasStandardType?entryTypeIsOwn(rawType):categoryIsOwn(l.rawCategory),newType=own?'rural':'hotel',newOrigin=own?'Animal próprio':'Boitel',newEntryType=own?'Próprio':'Boitel';
    if(l.type!==newType||l.origin!==newOrigin||l.entryType!==newEntryType)changed=true;l.type=newType;l.origin=newOrigin;l.entryType=newEntryType;next.push(l);
  });
  if(next.length!==state.lots.length)changed=true;state.lots=next;if(changed)save();
}

function init(){
  normalizeFeedManagerLots();state.year=new Date().getFullYear();updateHorizonLabels();
  document.querySelectorAll('.nav-item').forEach(function(b){b.addEventListener('click',function(){go(b.dataset.page);});});
  document.querySelectorAll('[data-go]').forEach(function(b){b.addEventListener('click',function(){go(b.dataset.go);});});
  el('mobileMenu').onclick=function(){document.querySelector('.sidebar').classList.toggle('open');};
  el('importPlanBtn').onclick=function(){el('importPlanInput').click();};el('openRuralImport').onclick=function(){el('importPlanInput').click();};
  el('importPlanInput').onchange=importPlanningFiles;
  el('importActiveBtn').onclick=function(){el('importActiveInput').click();};el('activePageImportBtn').onclick=function(){el('importActiveInput').click();};el('penPageImportBtn').onclick=function(){el('importActiveInput').click();};el('importActiveInput').onchange=importActivePdf;
  el('penImportShipmentBtn').onclick=function(){el('penShipmentInput').click();};el('penShipmentInput').onchange=importShipmentPlan;
  el('importBackupBtn').onclick=function(){el('importBackupInput').click();};el('importBackupInput').onchange=importBackup;
  el('exportBtn').onclick=exportBackup;el('printBtn').onclick=function(){window.print();};
  el('overviewRange').onchange=function(){renderOverview(model());};
  el('cashRange').onchange=function(){renderOverview(model());};
  el('compositionMonth').onchange=function(){renderOverview(model());};
  el('capacityRange').onchange=function(){renderCapacity(model());};
  el('horizonMonths').onchange=function(){state.horizonMonths=Number(this.value)===24?24:12;cashSelectedMonths=null;save();updateHorizonLabels();renderAll();showToast('Horizonte alterado para '+state.horizonMonths+' meses.');};
  el('currentCapacity').onchange=function(){setMonthCapacity(planningStartKey(),this.value);};
  el('capacityTable').onchange=function(e){if(e.target.matches('[data-capacity-month]'))setMonthCapacity(e.target.dataset.capacityMonth,e.target.value);};
  el('penBlockFilter').onchange=renderPens;el('penLineFilter').onchange=renderPens;el('penTypeFilter').onchange=renderPens;el('penStatusFilter').onchange=renderPens;
  el('penSearch').oninput=renderPens;el('penDietFilter').onchange=renderPens;el('penNoteFilter').onchange=renderPens;el('penConsMin').oninput=renderPens;el('penConsMax').oninput=renderPens;el('penDaysMin').oninput=renderPens;el('penDaysMax').oninput=renderPens;el('penShipmentDate').onchange=renderPens;
  el('clearPenFilters').onclick=function(){el('penBlockFilter').value='';el('penLineFilter').value='';el('penTypeFilter').value='';el('penStatusFilter').value='';el('penSearch').value='';el('penDietFilter').value='';el('penNoteFilter').value='';el('penConsMin').value='';el('penConsMax').value='';el('penDaysMin').value='';el('penDaysMax').value='';el('penShipmentDate').value='';renderPens();};
  var penQuickFilters=document.querySelector('.pen-quick-filters');if(penQuickFilters)penQuickFilters.onclick=function(e){var b=e.target.closest('button');if(!b)return;if(b.dataset.cons==='low'){el('penConsMin').value='';el('penConsMax').value='1.8';}if(b.dataset.cons==='high'){el('penConsMin').value='2.5';el('penConsMax').value='';}if(b.dataset.diet)el('penDietFilter').value=b.dataset.diet;if(b.dataset.notes)el('penNoteFilter').value=b.dataset.notes;if(b.dataset.days){var r=b.dataset.days.split('-');el('penDaysMin').value=r[0];el('penDaysMax').value=r[1];}renderPens();};
  el('penKpis').onclick=function(e){var b=e.target.closest('[data-kpi]');if(!b)return;if(b.dataset.kpi==='cons-low'){el('penConsMin').value='';el('penConsMax').value='1.8';el('penDietFilter').value='TERMINACAO';}if(b.dataset.kpi==='notes-active'){el('penNoteFilter').value='active';}renderPens();};
  el('shipmentSchedule').onclick=function(e){var b=e.target.closest('[data-shipment-date]');if(!b)return;el('penShipmentDate').value=b.dataset.shipmentDate;renderPens();};
  el('penBlocks').onchange=function(e){if(e.target.matches('[data-pen-block-name]')){var block=state.penBlocks.find(function(b){return b.id===e.target.dataset.penBlockName;});if(!block)return;block.name=String(e.target.value||'').trim()||('Bloco '+block.id);e.target.value=block.name;save();renderPens();showToast('Nome do bloco atualizado.');return;}var cb=e.target.closest('[data-pen-select]');if(!cb)return;if(cb.checked)penSelected.add(cb.dataset.penSelect);else penSelected.delete(cb.dataset.penSelect);updatePenSelectionBar();};
  el('penBlocks').onclick=function(e){var remove=e.target.closest('[data-delete-shipment]');if(remove){e.stopPropagation();deleteShipment(remove.dataset.deleteShipment);return;}if(e.target.closest('.pen-lot-select'))return;var row=e.target.closest('[data-pen-lot]');if(row){penDetailKey=row.dataset.penLot;renderPenDetail();el('penDrawer').hidden=false;return;}var card=e.target.closest('.pen-card');if(!card)return;var rows=card.querySelectorAll('[data-pen-lot]');if(rows.length===1){penDetailKey=rows[0].dataset.penLot;renderPenDetail();el('penDrawer').hidden=false;}};
  el('penSelectAllFiltered').onclick=function(){state.lots.filter(function(l){return l.source==='feedmanager'&&lotMatchesPenFilters(l);}).forEach(function(l){penSelected.add(lotKey(l));});renderPens();};
  el('penClearSelection').onclick=function(){penSelected.clear();renderPens();};
  el('penSelectionChips').addEventListener('click',function(e){var b=e.target.closest('[data-pen-deselect]');if(!b)return;penSelected.delete(b.dataset.penDeselect);renderPens();});
  el('penExportShipmentBtn').onclick=exportShipmentTemplate;el('penExportPrintBtn').onclick=exportPenPrint;el('penExportCsvBtn').onclick=exportPenCsv;
  window.addEventListener('afterprint',function(){document.body.classList.remove('print-pens');});
  el('closePenDrawer').onclick=function(){el('penDrawer').hidden=true;};el('penDrawer').onclick=function(e){if(e.target===this)this.hidden=true;};
  el('penDetailBody').addEventListener('click',function(e){var remove=e.target.closest('[data-delete-shipment]');if(remove){deleteShipment(remove.dataset.deleteShipment);return;}var b=e.target.closest('[data-close-note]');if(b)concludeNote(b.dataset.closeNote);});
  document.addEventListener('keydown',function(e){if(e.key==='Escape')el('penDrawer').hidden=true;});
  el('activeLineFilter').onchange=renderAnalysis;el('activeTypeFilter').onchange=renderAnalysis;el('activeExitFilter').onchange=renderAnalysis;el('useDaysFilter').onchange=renderAnalysis;el('activeDaysFilter').oninput=renderAnalysis;el('activeMaxDaysFilter').oninput=renderAnalysis;
  el('clearActiveFilters').onclick=function(){el('activeLineFilter').value='';el('activeTypeFilter').value='';el('activeExitFilter').value='';el('useDaysFilter').checked=false;el('activeDaysFilter').value=100;el('activeMaxDaysFilter').value=120;renderAnalysis();};
  el('page-analysis').onchange=function(e){if(e.target.matches('[data-report-lot]')){var lot=state.lots.find(function(l){return l.id===e.target.dataset.reportLot;});if(lot){lot.reportEnabled=e.target.checked;save();renderAnalysis();}}};
  el('page-analysis').onclick=function(e){var button=e.target.closest('[data-report-sort]');if(!button)return;var key=button.dataset.reportSort;if(reportSort.key===key)reportSort.dir*=-1;else reportSort={key:key,dir:1};renderAnalysis();};
  el('printAvailability').onclick=function(){document.body.classList.add('print-abate');window.print();};window.addEventListener('afterprint',function(){document.body.classList.remove('print-abate');});
  el('confirmPlanBtn').onclick=confirmPlan;
  el('defaultSale').onchange=updateDefaults;el('defaultBuy').onchange=updateDefaults;el('defaultHotel').onchange=updateDefaults;el('cashPaymentDays').onchange=updateCashSettings;el('cashAnticipate').onchange=updateCashSettings;el('cashInterestRate').onchange=updateCashSettings;
  el('cashMonthFilters').onclick=function(e){var button=e.target.closest('[data-cash-month]');if(!button)return;var key=button.dataset.cashMonth;if(key==='all'){cashSelectedMonths=null;}else if(cashSelectedMonths===null){cashSelectedMonths=new Set([key]);}else{if(cashSelectedMonths.has(key))cashSelectedMonths.delete(key);else cashSelectedMonths.add(key);if(!cashSelectedMonths.size)cashSelectedMonths=null;}renderCash(model());};
  document.querySelector('[data-close-modal]').onclick=closeModal;el('editModal').addEventListener('click',function(e){if(e.target===this)closeModal();});
  renderForms();renderAll();
}
function go(page){
  document.querySelectorAll('.page').forEach(function(p){p.classList.toggle('active',p.id==='page-'+page);});
  document.querySelectorAll('.nav-item').forEach(function(b){b.classList.toggle('active',b.dataset.page===page);});
  el('pageTitle').textContent=TITLES[page]||'';document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0);
}

function formMarkup(type,lot,isEdit){
  lot=lot||{};var entry=lot.entry||planningStartKey(),exit=lot.exit||addMonths(entry,3),nameLabel=type==='hotel'?'Nome do lote':'Identificação do lote';
  var originLabel=type==='rural'?'Fazenda de origem':type==='toreton'?'Fornecedor / origem':'Parceiro / cliente';
  var origin=lot.origin||'';var s='';
  s+='<label>'+nameLabel+'<input name="name" required maxlength="80" value="'+esc(lot.name||'')+'" placeholder="Ex.: Lote '+lotTypeLabel(type)+' 01"></label>';
  s+='<label>'+originLabel+'<input name="origin" required maxlength="80" value="'+esc(origin)+'" placeholder="'+(type==='hotel'?'Nome do parceiro':type==='rural'?'Nome da fazenda':'Origem da compra')+'"></label>';
  s+='<label>Quantidade de animais<input name="quantity" type="number" min="1" step="1" required value="'+(lot.quantity||'')+'" placeholder="0"></label>';
  s+='<label>Mês de entrada<input name="entry" type="month" min="'+planningStartKey()+'" required value="'+entry+'"></label>';
  s+='<label>Mês de saída<input name="exit" type="month" required value="'+exit+'"></label>';
  if(type==='rural')s+='<label>Venda por cabeça (US$)<input name="salePrice" type="number" min="0" step="10" required value="'+num(lot.salePrice||state.defaults.sale)+'"></label>';
  if(type==='toreton'){
    s+='<label>Compra por cabeça (US$)<input name="buyPrice" type="number" min="0" step="10" required value="'+num(lot.buyPrice||state.defaults.buy)+'"></label>';
    s+='<label>Venda por cabeça (US$)<input name="salePrice" type="number" min="0" step="10" required value="'+num(lot.salePrice||state.defaults.sale)+'"></label>';
  }
  if(type==='hotel')s+='<label>Hotelaria por cabeça (US$)<input name="hotelPrice" type="number" min="0" step="10" required value="'+num(lot.hotelPrice||state.defaults.hotel)+'"></label>';
  s+='<label class="full">Observação<input name="notes" maxlength="160" value="'+esc(lot.notes||'')+'" placeholder="Opcional"></label>';
  s+='<div class="form-actions">'+(isEdit?'<button type="button" class="btn ghost" data-close-edit>Cancelar</button>':'<button type="reset" class="btn ghost">Limpar</button>')+'<button type="submit" class="btn primary">'+(isEdit?'Salvar alterações':'Incluir lote')+'</button></div>';
  return s;
}
function wireForm(form,type,editId){
  var entry=form.elements.entry,exit=form.elements.exit,autoExit=!editId;
  entry.addEventListener('change',function(){if(autoExit||!exit.value)exit.value=addMonths(entry.value,3);});
  exit.addEventListener('change',function(){autoExit=false;});
  form.onsubmit=function(e){e.preventDefault();var f=new FormData(form);var q=Math.round(num(f.get('quantity'))),en=f.get('entry'),ex=f.get('exit');
    if(!q||!en||!ex){showToast('Preencha quantidade, entrada e saída.');return;}if(ex<=en){showToast('A saída precisa ser depois da entrada.');return;}
    var item={id:editId||uid(type),type:type,name:String(f.get('name')||'').trim(),origin:String(f.get('origin')||'').trim(),quantity:q,entry:en,exit:ex,notes:String(f.get('notes')||'').trim(),source:editId?(state.lots.find(function(x){return x.id===editId;})||{}).source||'manual':'manual'};
    if(type==='rural')item.salePrice=num(f.get('salePrice'));
    if(type==='toreton'){item.buyPrice=num(f.get('buyPrice'));item.salePrice=num(f.get('salePrice'));}
    if(type==='hotel')item.hotelPrice=num(f.get('hotelPrice'));
    if(editId){var i=state.lots.findIndex(function(x){return x.id===editId;});if(i>=0)state.lots[i]=Object.assign({},state.lots[i],item);}else state.lots.push(item);
    save();if(editId)closeModal();else{form.reset();renderForms();}renderAll();showToast(editId?'Lote atualizado.':'Lote incluído no planejamento.');
  };
  var c=form.querySelector('[data-close-edit]');if(c)c.onclick=closeModal;
}
function renderForms(){['rural','toreton','hotel'].forEach(function(type){var form=el(type+'Form');form.innerHTML=formMarkup(type,null,false);wireForm(form,type,null);});}
function editLot(id){var lot=state.lots.find(function(x){return x.id===id;});if(!lot)return;var form=el('editForm');form.innerHTML=formMarkup(lot.type,lot,true);wireForm(form,lot.type,id);el('editModal').hidden=false;}
function closeModal(){el('editModal').hidden=true;}
function deleteLot(id){var lot=state.lots.find(function(x){return x.id===id;});if(!lot)return;if(!confirm('Excluir o lote "'+lot.name+'"?'))return;state.lots=state.lots.filter(function(x){return x.id!==id;});save();renderAll();showToast('Lote excluído.');}

function model(){
  var keys=monthKeys(),start=planningStartKey(),cash=state.cash||defaults().cash,paymentMonths=Math.round(num(cash.paymentDays)/30),anticipate=!!cash.anticipate,annualRate=num(cash.annualInterest)/100,monthlyRate=Math.pow(1+annualRate,1/12)-1,interestFactor=Math.pow(1+monthlyRate,num(cash.paymentDays)/30)-1;var rows=keys.map(function(key){return {key:key,label:labelKey(key),capacity:capacityFor(key),rural:0,toreton:0,hotel:0,total:0,free:capacityFor(key),entries:{rural:0,toreton:0,hotel:0},exits:{rural:0,toreton:0,hotel:0},ruralSales:0,toretonSales:0,hotelRevenue:0,toretonPurchases:0,interestExpense:0,outflow:0};});
  state.lots.forEach(function(l){var isActive=l.source==='feedmanager',effectiveExit=isActive&&l.exit<start?start:l.exit,saleKey=isActive?addDaysToIso(l.entryDate,110).slice(0,7):effectiveExit;if(saleKey<start)saleKey=start;var receiptKey=anticipate?saleKey:addMonths(saleKey,paymentMonths),saleValue=num(l.quantity)*num(l.salePrice),interest=(anticipate&&(l.type==='rural'||l.type==='toreton'))?saleValue*interestFactor:0;rows.forEach(function(r){var occupies=l.entry<=r.key&&effectiveExit>=r.key;if(occupies){r[l.type]+=num(l.quantity);r.total+=num(l.quantity);}if(!isActive&&l.entry===r.key){r.entries[l.type]+=num(l.quantity);if(l.type==='toreton')r.toretonPurchases+=num(l.quantity)*num(l.buyPrice);}if(effectiveExit===r.key){r.exits[l.type]+=num(l.quantity);if(l.type==='hotel')r.hotelRevenue+=num(l.quantity)*num(l.hotelPrice);}if(r.key===receiptKey){if(l.type==='rural')r.ruralSales+=saleValue;if(l.type==='toreton')r.toretonSales+=saleValue;}if(r.key===saleKey)r.interestExpense+=interest;});});
  rows.forEach(function(r){r.free=r.capacity-r.total;r.entryTotal=r.entries.rural+r.entries.toreton+r.entries.hotel;r.exitTotal=r.exits.rural+r.exits.toreton+r.exits.hotel;r.revenue=r.ruralSales+r.toretonSales+r.hotelRevenue;r.outflow=r.toretonPurchases+r.interestExpense;r.net=r.revenue-r.outflow;});return rows;
}
function activeModel(){
  var keys=monthKeys(),start=planningStartKey(),rows=keys.map(function(key){return {key:key,label:labelKey(key),capacity:capacityFor(key),rural:0,toreton:0,hotel:0,total:0,free:capacityFor(key),entries:{rural:0,toreton:0,hotel:0},exits:{rural:0,toreton:0,hotel:0},ruralSales:0,toretonSales:0,hotelRevenue:0,toretonPurchases:0};});
  state.lots.filter(function(l){return l.source==='feedmanager';}).forEach(function(l){var forecast=addDaysToIso(l.entryDate,110).slice(0,7),shipment=shipmentFor(l),planned=shipment?Math.min(num(l.quantity),num(shipment.quantity)):0,parts=[];if(planned>0)parts.push({quantity:planned,exit:shipment.shipmentDate.slice(0,7)});if(num(l.quantity)-planned>0)parts.push({quantity:num(l.quantity)-planned,exit:forecast});parts.forEach(function(part){var effectiveExit=part.exit<start?start:part.exit;rows.forEach(function(r){if(l.entry<=r.key&&effectiveExit>=r.key){r[l.type]+=part.quantity;r.total+=part.quantity;}if(effectiveExit===r.key){r.exits[l.type]+=part.quantity;if(l.type==='rural')r.ruralSales+=part.quantity*num(l.salePrice);if(l.type==='hotel')r.hotelRevenue+=part.quantity*num(l.hotelPrice);}});});});
  rows.forEach(function(r){r.free=r.capacity-r.total;r.entryTotal=0;r.exitTotal=r.exits.rural+r.exits.hotel;r.revenue=r.ruralSales+r.hotelRevenue;r.net=r.revenue;});return rows;
}
function setMonthCapacity(key,value){var v=Math.round(num(value));if(v<1){showToast('Informe uma capacidade válida.');renderAll();return;}state.capacityByMonth=state.capacityByMonth||{};state.capacityByMonth[key]=v;save();renderAll();showToast('Capacidade de '+labelKey(key)+' atualizada.');}
function renderAll(){var m=model();renderHeaderPosition();renderOverview(activeModel());renderCapacity(m);renderActive();renderPens();renderAnalysis();renderType('rural',m);renderType('toreton',m);renderType('hotel',m);renderMovement(m);renderCash(m);renderPlans();}
function kpi(label,value,sub,cls,action){var tag=action?'button':'div';return '<'+tag+' class="kpi '+(cls||'')+(action?' clickable':'')+'"'+(action?' data-kpi="'+action+'" type="button"':'')+'><span>'+label+'</span><strong>'+value+'</strong><small>'+sub+(action?' · toque para filtrar':'')+'</small></'+tag+'>';}
function renderOverview(m){
  var peak=m.reduce(function(a,b){return b.total>a.total?b:a;},m[0]),ownExits=sum(m,function(r){return r.exits.rural;});
  el('overviewKpis').innerHTML=kpi('Capacidade atual',int(m[0].capacity),'vagas em '+m[0].label)+kpi('Animais atuais',int(m[0].total),'Próprio + Boitel')+kpi('Pico de ocupação',int(peak.total),peak.label+' · '+Math.round(peak.total/peak.capacity*100)+'%','gold')+kpi('Saída de boi próprio',int(ownExits),'RIP + Toreton + Compras','gold');
  var over=m.filter(function(r){return r.free<0;});el('overviewNotice').innerHTML=over.length?'<strong>Atenção:</strong> o plano ultrapassa a capacidade em '+over.map(function(r){return r.label;}).join(', ')+'. Ajuste os lotes ou as datas de entrada.':state.lots.length?'':'Comece importando as saídas do Planejamento Rural ou inclua lotes de Rural, Toreton e Hotelaria.';
  var range=Number(el('overviewRange').value)||4;el('occupancyChart').innerHTML=stackedChart(m.slice(0,range));
  var moves=m.filter(function(r){return r.entryTotal||r.exitTotal;}).slice(0,5);el('nextMoves').innerHTML=moves.length?moves.map(function(r){var text=[];if(r.entryTotal)text.push('ENTRAM '+int(r.entryTotal));if(r.exitTotal)text.push('SAEM '+int(r.exitTotal));return '<div class="decision-item"><div class="decision-month">'+r.label+'</div><div><strong>'+text.join(' · ')+' ANIMAIS</strong><span>'+int(Math.max(0,r.free))+' vagas disponíveis após os movimentos</span></div></div>';}).join(''):'<div class="empty-state">Nenhum movimento previsto nos próximos '+horizonMonths()+' meses.</div>';
  var cashRange=Number(el('cashRange').value)||4;el('cashMiniChart').innerHTML=cashFlowChart(model().slice(0,cashRange),230);
  var monthSelect=el('compositionMonth'),selectedMonth=monthSelect.value||m[0].key;monthSelect.innerHTML=m.map(function(r){return '<option value="'+r.key+'">'+r.label+'</option>';}).join('');if(!m.some(function(r){return r.key===selectedMonth;}))selectedMonth=m[0].key;monthSelect.value=selectedMonth;
  var composition=m.find(function(r){return r.key===selectedMonth;})||m[0],compositionTotal=composition.total||1;
  el('compositionPanel').innerHTML=['rural','toreton','hotel'].map(function(t){var pct=composition.total?Math.round(composition[t]/compositionTotal*100):0;return '<div class="composition-row"><div class="composition-label"><span>'+lotTypeLabel(t)+'</span><strong>'+int(composition[t])+' · '+pct+'%</strong></div><div class="bar-track"><div class="bar-fill '+t+'" style="width:'+pct+'%"></div></div></div>';}).join('')+'<p class="composition-note">'+(composition.total?'Composição das '+int(composition.total)+' vagas ocupadas em '+composition.label+'.':'Nenhuma vaga ocupada em '+composition.label+'.')+'</p>';
}
function renderCapacity(m){
  var h='<thead><tr><th>Origem</th>'+m.map(function(r){return '<th>'+r.label+'</th>';}).join('')+'<th>Média</th></tr></thead><tbody>';
  h+='<tr class="capacity-edit-row"><td>Capacidade</td>'+m.map(function(r){return '<td><input type="number" min="1" step="100" value="'+r.capacity+'" data-capacity-month="'+r.key+'" aria-label="Capacidade de '+r.label+'"></td>';}).join('')+'<td>'+int(sum(m,function(r){return r.capacity;})/m.length)+'</td></tr>';
  [['Rural','rural'],['Toreton','toreton'],['Hotelaria','hotel'],['Ocupado','total'],['Vagas livres','free']].forEach(function(row,ri){h+='<tr class="'+(ri>=3?'total-row':'')+'"><td>'+row[0]+'</td>'+m.map(function(r){var v=r[row[1]];return '<td class="'+(row[1]==='free'?(v<0?'danger-cell':'free-cell'):'')+'">'+int(v)+'</td>';}).join('')+'<td>'+int(sum(m,function(r){return r[row[1]];})/m.length)+'</td></tr>';});h+='</tbody>';el('capacityTable').innerHTML=h;el('currentCapacity').value=m[0].capacity;var capacityRange=Number(el('capacityRange').value)||4;el('capacityChart').innerHTML=stackedChart(m.slice(0,capacityRange));
  var peak=m.reduce(function(a,b){return b.total>a.total?b:a;},m[0]);var emptiest=m.reduce(function(a,b){return b.total<a.total?b:a;},m[0]);var overloaded=m.filter(function(r){return r.free<0;});
  var finalLots=state.lots.filter(function(l){var effectiveExit=l.source==='feedmanager'&&l.exit<planningStartKey()?planningStartKey():l.exit;return l.entry<=m[m.length-1].key&&effectiveExit>=m[m.length-1].key;}),insights='<div class="insight"><strong>Pico em '+peak.label+': '+int(peak.total)+' animais</strong><span>'+Math.round(peak.total/peak.capacity*100)+'% da capacidade do mês, com '+int(peak.free)+' vagas livres.</span></div>'+'<div class="insight"><strong>Maior espaço em '+emptiest.label+': '+int(emptiest.free)+' vagas</strong><span>Capacidade menos todos os lotes previstos para o mês.</span></div>';
  if(finalLots.length)insights+='<div class="insight warning"><strong>'+int(sum(finalLots,function(l){return l.quantity;}))+' animais permanecem no fim da projeção</strong><span>'+finalLots.map(function(l){return esc(l.name)+' — saída '+labelKey(l.exit);}).join('<br>')+'</span></div>';if(overloaded.length)insights+='<div class="insight danger"><strong>Capacidade ultrapassada</strong><span>Ajuste '+overloaded.map(function(r){return r.label+' ('+int(Math.abs(r.free))+' acima)';}).join(', ')+'.</span></div>';else insights+='<div class="insight"><strong>Plano dentro da capacidade</strong><span>Nenhum mês supera a capacidade definida.</span></div>';el('capacityInsights').innerHTML=insights;
}
function renderActive(){
  var lots=state.lots.filter(function(l){return l.source==='feedmanager';});
  var reportDate=activeReportDate();
  el('activeNotice').innerHTML=lots.length?'<strong>Posição em '+esc(formatIsoDate(reportDate))+freshnessLabel(reportDate)+'.</strong> RIP, Toreton e Compras são Próprio; qualquer outra categoria é Boitel. PASTO não é incluído.':'Importe o relatório PDF para criar o banco de lotes ativos.';
  var h='<thead><tr><th>Lote / curral</th><th>Classificação</th><th>Categoria do relatório</th><th>Ativos</th><th>Entrada</th><th>Saída (120 dias)</th><th>Linha</th></tr></thead><tbody>';
  if(!lots.length)h+='<tr><td colspan="7"><div class="empty-state">Nenhum relatório de lotes ativos importado.</div></td></tr>';
  lots.slice().sort(function(a,b){return (a.line+a.pen).localeCompare(b.line+b.pen,undefined,{numeric:true});}).forEach(function(l){h+='<tr><td><strong>'+esc(l.name)+'</strong><br><small>Curral '+esc(l.pen||'—')+'</small></td><td><span class="pill '+l.type+'">'+(l.type==='rural'?'Próprio':'Boitel')+'</span></td><td>'+esc(l.rawCategory||'—')+'</td><td>'+int(l.quantity)+'</td><td>'+formatMonthOrDate(l.entryDate,l.entry)+'</td><td>'+formatMonthOrDate(l.exitDate,l.exit)+'</td><td>'+esc(l.line||'—')+'</td></tr>';});
  el('activeTable').innerHTML=h+'</tbody>';
}
function penNumber(lot){var raw=String(lot.pen||'').toUpperCase(),m=raw.match(/(\d{1,2})/);return m?String(Number(m[1])).padStart(2,'0'):'';}
function lotMatchesPenFilters(l){
  var q=normalizedCategory(el('penSearch').value),diet=el('penDietFilter').value,note=el('penNoteFilter').value,min=inputNumber(el('penConsMin').value),max=inputNumber(el('penConsMax').value),daysMin=inputNumber(el('penDaysMin').value),daysMax=inputNumber(el('penDaysMax').value),shipmentDate=el('penShipmentDate').value,shipment=shipmentFor(l);
  var notesCount=activeNotes(l).length,search=!q||normalizedCategory(l.name+' '+l.pen+' '+l.line+' '+(l.rawCategory||'')).indexOf(q)>=0;
  return search&&(!diet||normalizedCategory(l.diet)===diet)&&(!note||(note==='active'?notesCount>0:notesCount===0))&&(min===null||l.pv>=min)&&(max===null||l.pv<=max)&&(daysMin===null||l.days>=daysMin)&&(daysMax===null||l.days<=daysMax)&&(!shipmentDate||(shipmentDate==='none'?!shipment:!!shipment&&shipment.shipmentDate===shipmentDate));
}
function penMapData(applyFilters){
  var map={};state.lots.filter(function(l){return l.source==='feedmanager'&&(applyFilters===false||lotMatchesPenFilters(l));}).forEach(function(l){var line=String(l.line||'').trim().toUpperCase(),number=penNumber(l);if(!/^[A-P]$/.test(line)||!number||Number(number)>10)return;var key=line+number;if(!map[key])map[key]={key:key,line:line,number:number,lots:[],quantity:0,types:{rural:0,hotel:0}};map[key].lots.push(l);map[key].quantity+=num(l.quantity);map[key].types[l.type]=(map[key].types[l.type]||0)+num(l.quantity);});return map;
}
function buildAllPens(map){var all=[];state.penBlocks.forEach(function(block){block.lines.forEach(function(line){for(var n=1;n<=10;n++){var key=line+String(n).padStart(2,'0'),pen=map[key]||{key:key,line:line,number:String(n).padStart(2,'0'),lots:[],quantity:0,types:{rural:0,hotel:0}};pen.blockId=block.id;all.push(pen);}});});return all;}
function penStatus(pen){if(!pen||!pen.quantity)return 'empty';if(pen.quantity>160)return 'over';if(pen.quantity===160)return 'full';return 'partial';}
function fillPenFilters(){
  var diet=el('penDietFilter').value,note=el('penNoteFilter').value,shipmentDate=el('penShipmentDate').value;
  var diets=Array.from(new Set(state.lots.filter(function(l){return l.source==='feedmanager';}).map(function(l){return normalizedCategory(l.diet);}))).filter(Boolean).sort();
  el('penDietFilter').innerHTML='<option value="">Todas</option>'+diets.map(function(d){return '<option value="'+esc(d)+'">'+esc(d)+'</option>';}).join('');
  var shipmentDates=Array.from(new Set((state.shipmentPlans||[]).map(function(p){return p.shipmentDate;}))).filter(Boolean).sort();
  el('penShipmentDate').innerHTML='<option value="">Todas</option><option value="none">Sem programação</option>'+shipmentDates.map(function(d){return '<option value="'+d+'">'+formatIsoDate(d)+'</option>';}).join('');
  el('penDietFilter').value=diet;el('penNoteFilter').value=note;el('penShipmentDate').value=shipmentDate;
}
function renderShipmentSchedule(){var current={};state.lots.filter(function(l){return l.source==='feedmanager';}).forEach(function(l){current[lotKey(l)]=l;});var groups={};(state.shipmentPlans||[]).forEach(function(p){var l=current[p.lotKey];if(!l||!p.shipmentDate)return;(groups[p.shipmentDate]||(groups[p.shipmentDate]=[])).push({plan:p,lot:l});});var dates=Object.keys(groups).sort(),box=el('shipmentSchedule');if(!dates.length){box.innerHTML='<div><strong>Embarques programados</strong><span>Nenhuma programação importada.</span></div>';return;}box.innerHTML='<div class="shipment-title"><strong>Embarques programados</strong><span>Toque em uma data para mostrar os currais.</span></div><div class="shipment-days">'+dates.map(function(d){var rows=groups[d],animals=sum(rows,function(x){return x.plan.quantity;}),pens=Array.from(new Set(rows.map(function(x){return x.lot.pen;}))).join(', ');return '<button type="button" data-shipment-date="'+d+'"><strong>'+formatIsoDate(d)+'</strong><span>'+int(animals)+' animais</span><small>'+esc(pens)+'</small></button>';}).join('')+'</div>';}
function renderPens(){
  fillPenFilters();
  var map=penMapData(),all=buildAllPens(map);
  var allFull=buildAllPens(penMapData(false));
  var allFeedLots=state.lots.filter(function(l){return l.source==='feedmanager';}),term=allFeedLots.filter(function(l){return normalizedCategory(l.diet)==='TERMINACAO';}),termLow=term.filter(function(l){return l.pv<1.8;}),activeNotesCount=state.notes.filter(function(n){return n.status==='active';}).length;
  var occupied=allFull.filter(function(p){return p.quantity>0;}),empty=allFull.length-occupied.length,animals=sum(occupied,function(p){return p.quantity;}),internal=sum(occupied,function(p){return Math.max(0,160-p.quantity);}),plannedVacant=occupied.filter(function(p){return p.lots.length&&p.lots.every(function(l){var s=shipmentFor(l);return s&&num(s.quantity)>=num(l.quantity);});});
  el('penKpis').innerHTML=kpi('Capacidade física',int(allFull.length*160),allFull.length+' currais × 160')+kpi('Animais alojados',int(animals),occupied.length+' currais ocupados')+kpi('Capacidade operacional livre',int(empty*160),empty+' currais vazios × 160','gold')+kpi('Vagas após embarques',int((empty+plannedVacant.length)*160),plannedVacant.length+' currais com saída total programada','green')+kpi('Espaço perdido',int(internal),'dentro de currais já ocupados','blue')+kpi('Consumo abaixo de 1,8% (terminação)',int(sum(termLow,function(x){return x.quantity;})),'animais em terminação para observar','red','cons-low')+kpi('Anotações ativas',int(activeNotesCount),'acompanhamentos pendentes','blue','notes-active');
  var blockFilter=el('penBlockFilter'),lineFilter=el('penLineFilter'),selectedBlock=blockFilter.value,selectedLine=lineFilter.value,typeFilter=el('penTypeFilter').value,statusFilter=el('penStatusFilter').value;
  var contentFilterActive=!!(String(el('penSearch').value||'').trim()||el('penDietFilter').value||el('penNoteFilter').value||String(el('penConsMin').value||'').trim()||String(el('penConsMax').value||'').trim()||String(el('penDaysMin').value||'').trim()||String(el('penDaysMax').value||'').trim()||el('penShipmentDate').value);
  blockFilter.innerHTML='<option value="">Todos</option>'+state.penBlocks.map(function(b){return '<option value="'+esc(b.id)+'">'+esc(b.name)+'</option>';}).join('');blockFilter.value=selectedBlock;
  lineFilter.innerHTML='<option value="">Todas</option>'+'ABCDEFGHIJKLMNOP'.split('').map(function(l){return '<option value="'+l+'">Linha '+l+'</option>';}).join('');lineFilter.value=selectedLine;
  var blocks=state.penBlocks.filter(function(b){return !selectedBlock||b.id===selectedBlock;}).map(function(block){var lines=block.lines.filter(function(line){return !selectedLine||line===selectedLine;});var lineHtml=lines.map(function(line){var pens=all.filter(function(p){return p.line===line;}).filter(function(p){var status=penStatus(p),contentMatch=!contentFilterActive||p.quantity>0,typeMatch=!typeFilter||(p.types[typeFilter]||0)>0,statusMatch=!statusFilter||(statusFilter==='occupied'?status!=='empty':status===statusFilter);return contentMatch&&typeMatch&&statusMatch;});if(!pens.length)return '';return '<section class="pen-line"><div class="pen-line-head"><strong>Linha '+line+'</strong><span>'+pens.filter(function(p){return p.quantity>0;}).length+' ocupadas</span></div><div class="pen-grid">'+pens.map(renderPenCard).join('')+'</div></section>';}).join('');if(!lineHtml)return '';return '<section class="pen-block"><div class="pen-block-head"><div><span class="section-tag">SETOR '+esc(block.id)+'</span><input data-pen-block-name="'+esc(block.id)+'" value="'+esc(block.name)+'" maxlength="30" aria-label="Nome do bloco '+esc(block.id)+'"></div><span>Linhas '+block.lines[0]+'–'+block.lines[block.lines.length-1]+'</span></div>'+lineHtml+'</section>';}).join('');
  el('penBlocks').innerHTML=blocks||'<div class="empty-state">Nenhum curral corresponde aos filtros escolhidos.</div>';renderShipmentSchedule();
  updatePenSelectionBar();
}
function penCardStatusTitle(status,free){return status==='empty'?'Curral disponível':status==='over'?'Capacidade ultrapassada':status==='full'?'Curral lotado':free+' lugares perdidos';}
function penLotRow(l){
  var notesCount=activeNotes(l).length,key=lotKey(l),checked=penSelected.has(key),alert=l.pv<1.8||l.pv>2.5,shipment=shipmentFor(l);
  return '<div class="pen-lot-row'+(alert?' alert':'')+(notesCount?' has-note':'')+(shipment?' scheduled':'')+'" data-pen-lot="'+esc(key)+'">'
    +'<label class="pen-lot-select" title="Selecionar para exportar" onclick="event.stopPropagation()"><input type="checkbox" data-pen-select="'+esc(key)+'"'+(checked?' checked':'')+'></label>'
    +'<div class="pen-lot-main"><span class="pen-lot-name">'+esc(l.name)+' · '+int(l.quantity)+' · '+(l.type==='rural'?'Próprio':'Boitel')+'</span>'
    +'<span class="pen-lot-meta">'+esc(l.diet||'—')+' · '+decimal(l.pv,2)+'% PV · '+int(l.days)+'d conf.'+(notesCount?' · ● '+notesCount+' anot.':'')+'</span>'+(shipment?'<span class="shipment-badge">Embarque '+formatIsoDate(shipment.shipmentDate)+' · '+int(shipment.quantity)+' animais<button type="button" data-delete-shipment="'+esc(key)+'" title="Excluir embarque" aria-label="Excluir embarque">×</button></span>':'')+'</div></div>';
}
function renderPenCard(p){
  var status=penStatus(p),dominant=p.types.rural>=p.types.hotel?'rural':'hotel',hasShipment=p.lots.some(function(l){return !!shipmentFor(l);}),cls=status==='empty'?'empty':status==='over'?'over':dominant,free=Math.max(0,160-p.quantity),title=penCardStatusTitle(status,free);
  var lotsHtml=p.lots.map(penLotRow).join('');
  return '<article class="pen-card '+cls+(hasShipment?' scheduled':'')+'"><div class="pen-card-top"><strong>'+p.key+'</strong><span>'+(hasShipment?'Saída programada':title)+'</span></div>'+(status==='empty'?'<div class="pen-empty-mark">Livre</div>':'<div class="pen-count"><strong>'+int(p.quantity)+'</strong><span>de 160 animais</span></div><div class="pen-meter"><i style="width:'+Math.min(100,p.quantity/160*100)+'%"></i></div><div class="pen-lots">'+lotsHtml+'</div>')+'</article>';
}
function penSelectedLots(){var valid={};state.lots.forEach(function(l){if(l.source==='feedmanager')valid[lotKey(l)]=l;});Array.from(penSelected).forEach(function(k){if(!valid[k])penSelected.delete(k);});return Array.from(penSelected).map(function(k){return valid[k];}).filter(Boolean);}
function updatePenSelectionBar(){var lots=penSelectedLots().sort(function(a,b){return (a.line+a.pen).localeCompare(b.line+b.pen,undefined,{numeric:true});}),bar=el('penSelectionBar');if(!bar)return;if(!lots.length){bar.hidden=true;return;}bar.hidden=false;el('penSelectionSummary').textContent=lots.length+' lote'+(lots.length===1?'':'s')+' selecionado'+(lots.length===1?'':'s')+' · '+int(sum(lots,function(x){return x.quantity;}))+' animais';el('penSelectionChips').innerHTML=lots.map(function(l){return '<span class="selection-chip">'+esc(l.pen)+' · '+esc(l.name)+'<button type="button" data-pen-deselect="'+esc(lotKey(l))+'" title="Remover da seleção" aria-label="Remover">×</button></span>';}).join('');}
function penDetailLot(){return state.lots.find(function(l){return l.source==='feedmanager'&&lotKey(l)===penDetailKey;});}
function penDetailItem(label,value){return '<div class="detail-item"><span>'+label+'</span><strong>'+esc(value==null||value===''?'—':value)+'</strong></div>';}
function renderPenDetail(){
  var l=penDetailLot();if(!l){el('penDrawer').hidden=true;return;}
  el('penDetailTitle').textContent='Curral '+l.pen+' · '+l.name;
  var lk=lotKey(l),shipment=shipmentFor(l),related=state.notes.filter(function(n){return (n.scope==='lot'&&n.targetKey===lk)||(n.scope==='pen'&&n.targetKey===l.pen);}).sort(function(a,b){return b.createdAt.localeCompare(a.createdAt);});
  el('penDetailBody').innerHTML=(shipment?'<div class="shipment-detail"><button type="button" data-delete-shipment="'+esc(lk)+'" title="Excluir embarque" aria-label="Excluir embarque">×</button><strong>Embarque programado para '+formatIsoDate(shipment.shipmentDate)+'</strong><span>'+int(shipment.quantity)+' animais'+(shipment.note?' · '+esc(shipment.note):'')+'</span></div>':'')+'<div class="detail-hero"><div class="detail-box"><span>Animais</span><strong>'+int(l.quantity)+'</strong></div><div class="detail-box"><span>Dieta</span><strong>'+esc(l.diet)+'</strong></div><div class="detail-box"><span>Consumo %PV</span><strong>'+decimal(l.pv,2)+'%</strong></div><div class="detail-box"><span>Dias confinamento</span><strong>'+int(l.days)+'</strong></div></div><div class="detail-grid">'
    +penDetailItem('Categoria / dono',l.rawCategory)+penDetailItem('Tipo',l.type==='rural'?'Próprio':'Boitel')+penDetailItem('Raça',l.breed)+penDetailItem('Entrada',formatIsoDate(l.entryDate))+penDetailItem('Peso entrada',decimal(l.entryWeight,1)+' kg')+penDetailItem('Peso estimado',decimal(l.estimatedWeight,1)+' kg')+penDetailItem('Peso de saída',decimal(l.exitWeight,1)+' kg')+penDetailItem('Saída estimada (relatório)',formatIsoDate(l.estimatedExit))+penDetailItem('Saída prevista (120 dias)',formatIsoDate(l.exitDate))+penDetailItem('GMD',decimal(l.gmd,2)+' kg/dia')+penDetailItem('Consumo MS por cabeça',decimal(l.kgCabMS,2)+' kg/dia')+penDetailItem('Consumo MS total da baia',decimal(l.kgCabMS*l.quantity,1)+' kg/dia')+penDetailItem('Consumo MN por cabeça',decimal(l.kgCabMN,2)+' kg/dia')+penDetailItem('Consumo MN total da baia',state.hasConsumo!==false?decimal(l.consumption,1)+' kg/dia':'não informado neste relatório')+penDetailItem('Dias de trato',int(l.treatmentDays))+penDetailItem('Mortes',int(l.deaths))
    +'</div><div class="notes-layout"><form class="note-form" id="penNoteForm"><h3>Nova anotação</h3><label>A anotação acompanha<select name="scope"><option value="lot">Este lote, mesmo se mudar de curral</option><option value="pen">Este curral</option></select></label><label>Anotação<textarea name="text" required placeholder="Registre o que foi observado e o que precisa ser acompanhado."></textarea></label><div class="note-actions"><button class="btn primary" type="submit">Salvar anotação</button><button class="btn secondary" type="button" id="closePenNotesBtn">Concluir anotações do curral</button></div></form><section class="notes-panel"><h3>Histórico</h3>'+(related.length?related.map(noteCard).join(''):'<div class="empty-state">Nenhuma anotação registrada.</div>')+'</section></div>';
  el('penNoteForm').onsubmit=addNote;el('closePenNotesBtn').onclick=closePenNotes;
}
function penExportRows(){return penSelectedLots().sort(function(a,b){return (a.line+a.pen).localeCompare(b.line+b.pen,undefined,{numeric:true});});}
function exportPenPrint(){var lots=penExportRows();if(!lots.length){showToast('Selecione ao menos um lote para exportar.');return;}
  var rows=lots.map(function(l){return '<tr><td>'+esc(l.line)+'</td><td>'+esc(l.pen)+'</td><td>'+esc(l.name)+'</td><td>'+esc(l.rawCategory||'')+'</td><td>'+(l.type==='rural'?'Próprio':'Boitel')+'</td><td>'+esc(l.breed||'')+'</td><td>'+esc(l.diet||'')+'</td><td>'+int(l.quantity)+'</td><td>'+decimal(l.pv,2)+'%</td><td>'+int(l.days)+'</td><td>'+decimal(l.estimatedWeight,1)+'</td><td>'+formatIsoDate(l.exitDate)+'</td></tr>';}).join('');
  el('penPrintArea').innerHTML='<h1>Rural Conf. — Lotes selecionados (Mapa dos Currais)</h1><p>Posição em '+formatIsoDate(activeReportDate())+' · gerado em '+new Date().toLocaleString('pt-BR')+' · '+lots.length+' lote'+(lots.length===1?'':'s')+' · '+int(sum(lots,function(x){return x.quantity;}))+' animais</p><table><thead><tr><th>Linha</th><th>Curral</th><th>Lote</th><th>Categoria/Dono</th><th>Tipo</th><th>Raça</th><th>Dieta</th><th>Animais</th><th>Consumo %PV</th><th>Dias conf.</th><th>Peso est. (kg)</th><th>Saída prevista</th></tr></thead><tbody>'+rows+'</tbody></table>';
  document.body.classList.add('print-pens');window.print();
}
function csvField(v){var s=String(v==null?'':v);return /[;"\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function exportPenCsv(){var lots=penExportRows();if(!lots.length){showToast('Selecione ao menos um lote para exportar.');return;}
  var head=['Linha','Curral','Lote','Categoria/Dono','Tipo','Raça','Dieta','Animais','Consumo %PV','Dias confinamento','Peso estimado (kg)','Saída prevista'],rows=lots.map(function(l){return [l.line,l.pen,l.name,l.rawCategory||'',l.type==='rural'?'Próprio':'Boitel',l.breed||'',l.diet||'',l.quantity,decimal(l.pv,2),l.days,decimal(l.estimatedWeight,1),formatIsoDate(l.exitDate)].map(csvField).join(';');});
  download('Lotes_selecionados_'+state.year+'_'+Date.now()+'.csv','﻿'+[head.join(';')].concat(rows).join('\r\n'),'text/csv');
  showToast(lots.length+' lote'+(lots.length===1?'':'s')+' exportado'+(lots.length===1?'':'s')+' em CSV.');
}
function csvSafe(v){var s=String(v==null?'':v);if(/^[=+\-@]/.test(s))s="'"+s;return csvField(s);}
function exportShipmentTemplate(){var lots=penExportRows();if(!lots.length){showToast('Selecione no mapa os lotes que serão programados.');return;}var title=['Programação de Abate Confinamento Ypoti','','','','','','','','','','',''],instruction=['Preenchimento obrigatório: mantenha o lote exatamente como consta no Relatório de Lotes Ativos e informe a data de embarque em DD/MM/AAAA.','','','','','','','','','','',''],head=['Enviar','Linha','Curral','Lote','Data de entrada','Categoria/Dono','Tipo','Animais do lote','Quantidade para abate','Data do embarque (DD/MM/AAAA)','Observação','Identificador'];var rows=lots.map(function(l){var p=shipmentFor(l);return ['SIM',l.line,l.pen,l.name,formatIsoDate(l.entryDate),l.rawCategory||'',l.type==='rural'?'Próprio':'Boitel',l.quantity,p?p.quantity:l.quantity,p?formatIsoDate(p.shipmentDate):'',p?p.note:'',lotKey(l)].map(csvSafe).join(';');});var content=[title.map(csvSafe).join(';'),instruction.map(csvSafe).join(';'),'',head.join(';')].concat(rows).join('\r\n');download('Programacao_de_Abate_Confinamento_Ypoti_'+new Date().toISOString().slice(0,10)+'.csv','﻿'+content,'text/csv');showToast('Planilha criada com datas em DD/MM/AAAA. Lote e data de embarque são obrigatórios.');}
function parseCsv(text){var rows=[],row=[],cell='',quoted=false,s=String(text||'').replace(/^﻿/,'');for(var i=0;i<s.length;i++){var c=s[i];if(quoted){if(c==='"'&&s[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=false;else cell+=c;}else if(c==='"')quoted=true;else if(c===';'){row.push(cell);cell='';}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows;}
async function importShipmentPlan(e){var f=e.target.files&&e.target.files[0];if(!f)return;try{var rows=parseCsv(await f.text()),headerAt=rows.findIndex(function(r){return normalizedCategory(r[0])==='ENVIAR';});if(headerAt<0)throw new Error('Use a planilha exportada pelo Rural Conf.');rows=rows.slice(headerAt);if(rows.length<2)throw new Error('A planilha está vazia.');var headers=rows.shift().map(normalizedCategory),colPart=function(name){return headers.findIndex(function(h){return h.indexOf(normalizedCategory(name))>=0;});},iSend=colPart('Enviar'),iLot=colPart('Lote'),iQty=colPart('Quantidade para abate'),iDate=colPart('Data do embarque'),iNote=colPart('Observação'),iKey=colPart('Identificador');if(iLot<0||iDate<0)throw new Error('Use a planilha exportada pelo Rural Conf.');var current={},byName={};state.lots.filter(function(l){return l.source==='feedmanager';}).forEach(function(l){current[lotKey(l)]=l;byName[normalizedCategory(l.name)]=l;});var updated=0,removed=0,errors=[];rows.forEach(function(r,n){if(!r.some(function(v){return String(v||'').trim();}))return;var lotName=String(r[iLot]||'').trim(),key=iKey>=0?String(r[iKey]||'').trim():'',lot=current[key]||byName[normalizedCategory(lotName)],send=normalizedCategory(iSend>=0?r[iSend]:'SIM');if(!lotName){errors.push('lote obrigatório na linha '+(n+5));return;}if(!lot){errors.push('lote "'+lotName+'" não encontrado');return;}key=lotKey(lot);var existing=(state.shipmentPlans||[]).findIndex(function(p){return p.lotKey===key;});if(send==='NAO'||send==='REMOVER'){if(existing>=0){state.shipmentPlans.splice(existing,1);removed++;}return;}var date=parseShipmentDate(r[iDate]);if(!date){errors.push('data obrigatória para '+lotName+' em DD/MM/AAAA');return;}var quantity=Math.max(1,Math.min(num(lot.quantity),Math.round(inputNumber(iQty>=0?r[iQty]:'')||num(lot.quantity)))),plan={lotKey:key,lotName:lot.name,pen:lot.pen,shipmentDate:date,quantity:quantity,note:String(iNote>=0?r[iNote]||'':'').trim(),importedAt:new Date().toISOString()};if(existing>=0)state.shipmentPlans[existing]=plan;else state.shipmentPlans.push(plan);updated++;});save();renderPens();if(errors.length)showToast(updated+' programações importadas. Corrija: '+errors.slice(0,3).join('; ')+'.');else showToast(updated+' programações importadas'+(removed?' e '+removed+' removidas':'')+'.');}catch(err){showToast(err.message||'Não foi possível importar a programação.');}finally{e.target.value='';}}
function renderAnalysis(){
  var lots=state.lots.filter(function(l){return l.source==='feedmanager';});
  var lineSelect=el('activeLineFilter'),exitSelect=el('activeExitFilter'),selectedLine=lineSelect.value,selectedType=el('activeTypeFilter').value,selectedExit=exitSelect.value;
  var useDays=el('useDaysFilter').checked,days=Math.max(0,Math.round(num(el('activeDaysFilter').value))),maxDays=Math.max(days,Math.round(num(el('activeMaxDaysFilter').value)||days)),averageDays=useDays?Math.round((days+maxDays)/2):110;el('activeDaysFilter').value=days;el('activeMaxDaysFilter').value=maxDays;el('activeDaysFilter').disabled=!useDays;el('activeMaxDaysFilter').disabled=!useDays;
  var lines=Array.from(new Set(lots.map(function(l){return l.line;}))).filter(Boolean).sort(),exits=Array.from(new Set(lots.map(function(l){return addDaysToIso(l.entryDate,averageDays).slice(0,7);}))).filter(Boolean).sort();
  lineSelect.innerHTML='<option value="">Todas</option>'+lines.map(function(v){return '<option value="'+esc(v)+'">'+esc(v)+'</option>';}).join('');lineSelect.value=selectedLine;
  exitSelect.innerHTML='<option value="">Todos</option>'+exits.map(function(v){return '<option value="'+v+'">'+labelKey(v)+'</option>';}).join('');exitSelect.value=selectedExit;
  var baseLots=lots.filter(function(l){return (!selectedLine||l.line===selectedLine)&&(!selectedType||l.type===selectedType)&&(!selectedExit||addDaysToIso(l.entryDate,averageDays).slice(0,7)===selectedExit);});
  var candidateLots=baseLots.map(function(l){var date=addDaysToIso(l.entryDate,averageDays),day=Number(date.slice(8,10));return {lot:l,date:date,daysToday:Math.max(0,-daysFromToday(l.entryDate)),monthKey:date.slice(0,7),month:labelKey(date.slice(0,7)),fortnight:day<=15?'1ª quinzena':'2ª quinzena'};}).filter(function(x){return !useDays||(x.daysToday>=days&&x.daysToday<=maxDays);}),reportLots=candidateLots.filter(function(x){return x.lot.reportEnabled!==false;});
  var total=sum(candidateLots,function(x){return x.lot.quantity;}),own=sum(candidateLots,function(x){return x.lot.type==='rural'?x.lot.quantity:0;}),hotel=sum(candidateLots,function(x){return x.lot.type==='hotel'?x.lot.quantity:0;});
  el('analysisKpis').innerHTML=kpi('Animais filtrados',int(total),candidateLots.length+' lotes encontrados')+kpi('Animal próprio',int(own),'dentro dos filtros')+kpi('Boitel',int(hotel),'dentro dos filtros','blue')+kpi('Lotes encontrados',int(candidateLots.length),'resultado dos filtros','gold');
  var groups={};reportLots.forEach(function(x){var key=x.monthKey+'|'+x.fortnight;if(!groups[key])groups[key]={monthKey:x.monthKey,month:x.month,fortnight:x.fortnight,rural:0,hotel:0,total:0};groups[key][x.lot.type]+=num(x.lot.quantity);groups[key].total+=num(x.lot.quantity);});var reportGroups=Object.keys(groups).map(function(k){return groups[k];}).sort(function(a,b){return a.monthKey.localeCompare(b.monthKey)||a.fortnight.localeCompare(b.fortnight);}),today=new Date();
  el('availabilityHelp').textContent=useDays?'Quantidades por mês e quinzena, usando a média de '+averageDays+' dias.':'Todos os dias incluídos. A previsão usa 110 dias.';el('availabilityReportDate').textContent='Emitido em '+today.toLocaleDateString('pt-BR')+(useDays?' · intervalo de '+days+' a '+maxDays+' dias · média de '+averageDays+' dias':' · sem filtro de dias · previsão em 110 dias');
  var ah='<thead><tr><th>Mês</th><th>Período</th><th>Próprio</th><th>Boitel</th><th>Total de animais</th></tr></thead><tbody>';reportGroups.forEach(function(r){ah+='<tr><td><strong>'+r.month+'</strong></td><td>'+r.fortnight+'</td><td>'+int(r.rural)+'</td><td>'+int(r.hotel)+'</td><td class="report-total"><strong>'+int(r.total)+' animais</strong></td></tr>';});if(!reportGroups.length)ah+='<tr><td colspan="5">Nenhum lote selecionado para o relatório.</td></tr>';el('availabilityTable').innerHTML=ah+'</tbody>';
  function sortHead(label,key){var mark=reportSort.key===key?(reportSort.dir===1?' ↑':' ↓'):'';return '<th><button class="sort-button" type="button" data-report-sort="'+key+'">'+label+mark+'</button></th>';}
  var dh='<thead><tr><th class="report-check">Enviar</th>'+sortHead('Linha','line')+sortHead('Lote / curral','lot')+sortHead('Tipo','type')+sortHead('Animais','quantity')+sortHead('Dias hoje','days')+sortHead('Entrada','entry')+sortHead('Previsão ('+averageDays+' dias)','date')+sortHead('Quinzena','fortnight')+'</tr></thead><tbody>';candidateLots.sort(function(a,b){var av,bv,key=reportSort.key;if(key==='line'){av=a.lot.line+a.lot.pen;bv=b.lot.line+b.lot.pen;}else if(key==='lot'){av=a.lot.name+' '+a.lot.pen;bv=b.lot.name+' '+b.lot.pen;}else if(key==='type'){av=a.lot.type==='rural'?'Próprio':'Boitel';bv=b.lot.type==='rural'?'Próprio':'Boitel';}else if(key==='quantity'){av=num(a.lot.quantity);bv=num(b.lot.quantity);}else if(key==='days'){av=a.daysToday;bv=b.daysToday;}else if(key==='entry'){av=a.lot.entryDate;bv=b.lot.entryDate;}else if(key==='date'){av=a.date;bv=b.date;}else{av=a.fortnight;bv=b.fortnight;}var result=typeof av==='number'?av-bv:String(av).localeCompare(String(bv),undefined,{numeric:true});return result*reportSort.dir;}).forEach(function(x){var l=x.lot,enabled=l.reportEnabled!==false;dh+='<tr class="'+(enabled?'':'report-excluded')+'"><td class="report-check"><input type="checkbox" '+(enabled?'checked':'')+' data-report-lot="'+esc(l.id)+'" aria-label="Enviar '+esc(l.name)+' no relatório"></td><td><strong>'+esc(l.line||'—')+'</strong></td><td>'+esc(l.name)+' / '+esc(l.pen||'—')+'</td><td>'+(l.type==='rural'?'Próprio':'Boitel')+'</td><td><strong>'+int(l.quantity)+'</strong></td><td><strong>'+int(x.daysToday)+' dias</strong></td><td>'+formatIsoDate(l.entryDate)+'</td><td>'+formatIsoDate(x.date)+'</td><td>'+x.fortnight+'</td></tr>';});if(!candidateLots.length)dh+='<tr><td colspan="9">Nenhum lote corresponde aos filtros escolhidos.</td></tr>';el('availabilityDetails').innerHTML=dh+'</tbody>';
}
function formatIsoDate(v){if(!v)return '—';var p=v.split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:v;}
function formatMonthOrDate(date,month){return date?formatIsoDate(date):labelKey(month);}
function addDaysToIso(iso,days){if(!iso)return '';var d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+days);return keyOf(d.getFullYear(),d.getMonth())+'-'+String(d.getDate()).padStart(2,'0');}
function daysFromToday(iso){if(!iso)return 999999;var p=iso.split('-'),target=new Date(Number(p[0]),Number(p[1])-1,Number(p[2])),today=new Date();today.setHours(0,0,0,0);return Math.round((target-today)/86400000);}
function renderType(type,m){
  var lots=state.lots.filter(function(l){return l.type===type;});var qty=sum(lots,function(l){return l.quantity;});var annualValue=type==='rural'?sum(lots,function(l){return l.quantity*l.salePrice;}):type==='toreton'?sum(lots,function(l){return l.quantity*l.buyPrice;}):sum(lots,function(l){return l.quantity*l.hotelPrice;});var exitValue=type==='toreton'?sum(lots,function(l){return l.quantity*l.salePrice;}):annualValue;
  var title=type==='rural'?'Animais próprios planejados':type==='toreton'?'Toreton a comprar':'Vagas reservadas';var valueTitle=type==='hotel'?'Receita prevista':'Valor na saída';
  el(type+'Summary').innerHTML='<h2>'+title+'</h2><strong>'+int(qty)+' cabeças</strong><div class="summary-line"><span>'+valueTitle+'</span><b>'+usd(exitValue)+'</b></div>'+(type==='toreton'?'<div class="summary-line"><span>Capital de compra</span><b>'+usd(annualValue)+'</b></div><div class="summary-line"><span>Margem bruta prevista</span><b>'+usd(exitValue-annualValue)+'</b></div>':'')+'<div class="summary-line"><span>Quantidade de lotes</span><b>'+lots.length+'</b></div>';
  var h='<thead><tr><th>Lote / origem</th><th>Quantidade</th><th>Entrada</th><th>Saída</th><th>Permanência</th>';
  if(type==='rural')h+='<th>Venda/cab</th><th>Receita</th>';if(type==='toreton')h+='<th>Compra/cab</th><th>Venda/cab</th><th>Desembolso</th>';if(type==='hotel')h+='<th>Hotelaria/cab</th><th>Receita</th>';h+='<th>Origem</th><th>Ações</th></tr></thead><tbody>';
  if(!lots.length)h+='<tr><td colspan="11"><div class="empty-state">Nenhum lote de '+lotTypeLabel(type)+' incluído.</div></td></tr>';
  lots.sort(function(a,b){return a.entry.localeCompare(b.entry);}).forEach(function(l){var months=monthDiff(l.entry,l.exit),isActive=l.source==='feedmanager',sourceLabel=isActive?'Ativo':l.source==='planejamento'?'Importado':'Manual';h+='<tr><td><strong>'+esc(l.name)+'</strong><br><small>'+esc(l.origin)+'</small></td><td>'+int(l.quantity)+'</td><td>'+labelKey(l.entry)+'</td><td>'+labelKey(l.exit)+'</td><td>'+months+' meses</td>';if(type==='rural')h+='<td>'+usd(l.salePrice)+'</td><td>'+usd(l.quantity*l.salePrice)+'</td>';if(type==='toreton')h+='<td>'+usd(l.buyPrice)+'</td><td>'+usd(l.salePrice)+'</td><td>'+usd(l.quantity*l.buyPrice)+'</td>';if(type==='hotel')h+='<td>'+usd(l.hotelPrice)+'</td><td>'+usd(l.quantity*l.hotelPrice)+'</td>';h+='<td><span class="pill '+(isActive?'imported':type)+'">'+sourceLabel+'</span></td><td>'+(isActive?'<small>Somente leitura</small>':'<div class="table-actions"><button class="icon-btn" onclick="RP.edit(\''+l.id+'\')" title="Editar">✎</button><button class="icon-btn" onclick="RP.remove(\''+l.id+'\')" title="Excluir">×</button></div>')+'</td></tr>';});h+='</tbody>';el(type+'Table').innerHTML=h;
}
function monthDiff(a,b){var x=a.split('-'),y=b.split('-');return (Number(y[0])-Number(x[0]))*12+Number(y[1])-Number(x[1]);}
function renderMovement(m){var totalIn=sum(m,function(r){return r.entryTotal;}),totalOut=sum(m,function(r){return r.exitTotal;}),peakIn=m.reduce(function(a,b){return b.entryTotal>a.entryTotal?b:a;},m[0]);var peakOut=m.reduce(function(a,b){return b.exitTotal>a.exitTotal?b:a;},m[0]);
  el('movementKpis').innerHTML=kpi('Entradas no período',int(totalIn),'próximos '+horizonMonths()+' meses')+kpi('Saídas no período',int(totalOut),'próximos '+horizonMonths()+' meses','gold')+kpi('Maior entrada',int(peakIn.entryTotal),peakIn.label,'blue')+kpi('Maior saída',int(peakOut.exitTotal),peakOut.label,'gold')+kpi('Saldo de movimentos',int(totalIn-totalOut),'entradas menos saídas',totalIn-totalOut>0?'red':'');
  el('movementChart').innerHTML=movementBars(m);var h='<thead><tr><th>Movimento</th>'+m.map(function(r){return '<th>'+r.label+'</th>';}).join('')+'<th>Total</th></tr></thead><tbody>';
  [['Entrada Rural',function(r){return r.entries.rural;}],['Entrada Toreton',function(r){return r.entries.toreton;}],['Entrada Hotelaria',function(r){return r.entries.hotel;}],['Total de entradas',function(r){return r.entryTotal;}],['Saída Rural',function(r){return r.exits.rural;}],['Saída Toreton',function(r){return r.exits.toreton;}],['Saída Hotelaria',function(r){return r.exits.hotel;}],['Total de saídas',function(r){return r.exitTotal;}]].forEach(function(row,i){h+='<tr class="'+([3,7].indexOf(i)>=0?'total-row':'')+'"><td>'+row[0]+'</td>'+m.map(function(r){return '<td>'+int(row[1](r))+'</td>';}).join('')+'<td>'+int(sum(m,row[1]))+'</td></tr>';});h+='</tbody>';el('movementTable').innerHTML=h;
}
function renderCash(m){var cash=state.cash||defaults().cash,monthlyEquivalent=(Math.pow(1+num(cash.annualInterest)/100,1/12)-1)*100;el('defaultSale').value=state.defaults.sale;el('defaultBuy').value=state.defaults.buy;el('defaultHotel').value=state.defaults.hotel;el('cashPaymentDays').value=String(cash.paymentDays||0);el('cashAnticipate').value=String(!!cash.anticipate);el('cashInterestRate').value=num(cash.annualInterest);el('cashInterestRate').disabled=!cash.anticipate;el('cashRateHelp').textContent=monthlyEquivalent.toLocaleString('pt-BR',{minimumFractionDigits:4,maximumFractionDigits:4})+'% ao mês equivalente';el('cashMonthFilters').innerHTML='<button type="button" data-cash-month="all" class="month-chip '+(cashSelectedMonths===null?'active':'')+'" aria-pressed="'+(cashSelectedMonths===null)+'">Todos</button>'+m.map(function(r){var active=cashSelectedMonths!==null&&cashSelectedMonths.has(r.key);return '<button type="button" data-cash-month="'+r.key+'" class="month-chip '+(active?'active':'')+'" aria-pressed="'+active+'">'+r.label+'</button>';}).join('');
  var selected=cashSelectedMonths===null?m:m.filter(function(r){return cashSelectedMonths.has(r.key);}),rural=sum(selected,function(r){return r.ruralSales;}),tSale=sum(selected,function(r){return r.toretonSales;}),hotel=sum(selected,function(r){return r.hotelRevenue;}),buy=sum(selected,function(r){return r.toretonPurchases;}),interest=sum(selected,function(r){return r.interestExpense;}),net=rural+tSale+hotel-buy-interest;
  el('cashKpis').innerHTML=kpi('Recebimento Rural',usd(rural),'dinheiro disponível')+kpi('Recebimento Toreton',usd(tSale),'dinheiro disponível','gold')+kpi('Receita Hotelaria',usd(hotel),'cobrada na saída','blue')+kpi('Compra Toreton',usd(buy),'desembolso nas entradas','gold')+kpi('Juros bancários',usd(interest),'custo da antecipação','red')+kpi('Saldo disponível',usd(net),'entradas menos saídas',net<0?'red':'');el('cashChart').innerHTML=selected.length?cashBars(selected,340):'<div class="chart-empty">Selecione pelo menos um mês.</div>';
  var h='<thead><tr><th>Fluxo (US$)</th>'+selected.map(function(r){return '<th>'+r.label+'</th>';}).join('')+'<th>Total</th></tr></thead><tbody>';
  [['Recebimento Rural',function(r){return r.ruralSales;}],['Recebimento Toreton',function(r){return r.toretonSales;}],['Hotelaria',function(r){return r.hotelRevenue;}],['Total de entradas',function(r){return r.revenue;}],['Compra Toreton',function(r){return r.toretonPurchases;}],['Juros bancários',function(r){return r.interestExpense;}],['Total de saídas',function(r){return r.outflow;}],['Saldo disponível',function(r){return r.net;}]].forEach(function(row,i){h+='<tr class="'+([3,6,7].indexOf(i)>=0?'total-row':'')+'"><td>'+row[0]+'</td>'+selected.map(function(r){return '<td'+(row[1](r)<0?' class="danger-cell"':'')+'>'+usd(row[1](r))+'</td>';}).join('')+'<td>'+usd(sum(selected,row[1]))+'</td></tr>';});h+='</tbody>';el('cashTable').innerHTML=h;
}
function updateDefaults(){
  state.defaults.sale=num(el('defaultSale').value);
  state.defaults.buy=num(el('defaultBuy').value);
  state.defaults.hotel=num(el('defaultHotel').value);

  // Estes campos são as premissas financeiras do planejamento atual. Além de
  // servirem para novos lotes, precisam atualizar os lotes já carregados para
  // que o fluxo de caixa seja recalculado imediatamente com os novos valores.
  state.lots.forEach(function(l){
    if(l.type==='rural')l.salePrice=state.defaults.sale;
    if(l.type==='toreton'){
      l.buyPrice=state.defaults.buy;
      l.salePrice=state.defaults.sale;
    }
    if(l.type==='hotel')l.hotelPrice=state.defaults.hotel;
  });

  save();
  renderForms();
  renderAll();
  showToast('Valores financeiros aplicados a todos os lotes do planejamento atual.');
}
function updateCashSettings(){state.cash=state.cash||defaults().cash;state.cash.paymentDays=Math.max(0,Math.round(num(el('cashPaymentDays').value)));state.cash.anticipate=el('cashAnticipate').value==='true';state.cash.annualInterest=Math.max(0,num(el('cashInterestRate').value));save();renderAll();showToast('Condições de recebimento atualizadas.');}

function chartBase(h){return {w:1000,h:h||310,l:55,r:20,t:20,b:42};}
function quadrimesterChart(m){
  if(!state.lots.length)return '<div class="chart-empty">Inclua ou importe lotes para visualizar a ocupação.</div>';
  var groups=[m.slice(0,4),m.slice(4,8),m.slice(8,12)].map(function(rows){var g={rows:rows,rural:0,toreton:0,hotel:0,total:0};['rural','toreton','hotel','total'].forEach(function(k){g[k]=sum(rows,function(r){return r[k];})/rows.length;});g.free=CAPACITY-g.total;return g;}),c={w:1000,h:350,l:70,r:30,t:34,b:66},ph=c.h-c.t-c.b,max=CAPACITY*1.08,s='<svg viewBox="0 0 '+c.w+' '+c.h+'" role="img" aria-label="Ocupação média por quadrimestre">';
  for(var tick=0;tick<=4;tick++){var val=CAPACITY*tick/4,y=c.t+ph-ph*val/max;s+='<line x1="'+c.l+'" y1="'+y+'" x2="'+(c.w-c.r)+'" y2="'+y+'" stroke="#e5e9e5"/><text x="'+(c.l-10)+'" y="'+(y+4)+'" text-anchor="end" fill="#68756f" font-size="12">'+shortNum(val)+'</text>';}
  var capY=c.t+ph-ph*CAPACITY/max;s+='<line x1="'+c.l+'" y1="'+capY+'" x2="'+(c.w-c.r)+'" y2="'+capY+'" stroke="#b54336" stroke-width="2" stroke-dasharray="7 5"/><text x="'+(c.w-c.r)+'" y="'+(capY-7)+'" text-anchor="end" fill="#b54336" font-size="12" font-weight="700">CAPACIDADE '+int(CAPACITY)+'</text>';
  groups.forEach(function(g,i){var center=c.l+(i+.5)*(c.w-c.l-c.r)/3,bw=170,base=c.t+ph;[['rural','#2e6b45'],['toreton','#c38a2b'],['hotel','#28738a']].forEach(function(z,zi){var bh=ph*g[z[0]]/max;base-=bh;s+='<rect x="'+(center-bw/2)+'" y="'+base+'" width="'+bw+'" height="'+Math.max(0,bh)+'" rx="'+(zi===2?8:0)+'" fill="'+z[1]+'"><title>'+lotTypeLabel(z[0])+': '+int(g[z[0]])+'</title></rect>';});var first=g.rows[0].key.split('-'),last=g.rows[g.rows.length-1].key.split('-'),years=first[0]===last[0]?first[0]:first[0]+'–'+last[0];s+='<text x="'+center+'" y="'+Math.max(c.t+16,base-12)+'" text-anchor="middle" fill="#17342a" font-size="18" font-weight="900">'+int(g.total)+'</text><text x="'+center+'" y="'+(c.h-35)+'" text-anchor="middle" fill="#17342a" font-size="15" font-weight="900">'+MONTHS[Number(first[1])-1]+'–'+MONTHS[Number(last[1])-1]+'</text><text x="'+center+'" y="'+(c.h-16)+'" text-anchor="middle" fill="#68756f" font-size="12" font-weight="700">'+years+' · média ocupada</text>';});return s+'</svg>';
}
function availabilityBars(m){var c=chartBase(280),pw=c.w-c.l-c.r,ph=c.h-c.t-c.b,count=m.length||1,max=Math.max(1,Math.max.apply(null,m.map(function(r){return r.total;}))),bw=Math.min(90,pw/count*.42),s='<svg viewBox="0 0 '+c.w+' '+c.h+'" role="img" aria-label="Animais disponíveis para abate por mês">';for(var g=0;g<=4;g++){var val=max*g/4,y=c.t+ph-ph*g/4;s+='<line x1="'+c.l+'" y1="'+y+'" x2="'+(c.w-c.r)+'" y2="'+y+'" stroke="#edf0ed"/><text x="'+(c.l-8)+'" y="'+(y+4)+'" text-anchor="end" fill="#718078" font-size="11">'+shortNum(val)+'</text>';}
  m.forEach(function(r,i){var x=c.l+(i+.5)*pw/count-bw/2,base=c.t+ph,hotelH=ph*r.hotel/max,ruralH=ph*r.rural/max;base-=ruralH;s+='<rect x="'+x+'" y="'+base+'" width="'+bw+'" height="'+ruralH+'" rx="3" fill="#397552"><title>Próprio: '+int(r.rural)+'</title></rect>';base-=hotelH;s+='<rect x="'+x+'" y="'+base+'" width="'+bw+'" height="'+hotelH+'" rx="3" fill="#347e91"><title>Boitel: '+int(r.hotel)+'</title></rect>';if(r.total)s+='<text x="'+(x+bw/2)+'" y="'+Math.max(c.t+12,base-7)+'" text-anchor="middle" fill="#17342a" font-size="13" font-weight="650">'+int(r.total)+'</text>';s+='<text x="'+(x+bw/2)+'" y="'+(c.h-12)+'" text-anchor="middle" fill="#64736a" font-size="12" font-weight="600">'+r.label+'</text>';});return s+'</svg>';}
function stackedChart(m){if(!state.lots.length)return '<div class="chart-empty">Inclua ou importe lotes para visualizar a ocupação.</div>';var c=chartBase(300),pw=c.w-c.l-c.r,ph=c.h-c.t-c.b,count=m.length||1,max=Math.max.apply(null,m.map(function(x){return Math.max(x.capacity,x.total);}))*1.08,bw=Math.min(76,pw/count*.38),s='<svg viewBox="0 0 '+c.w+' '+c.h+'" role="img" aria-label="Ocupação mensal do confinamento">';for(var g=0;g<=4;g++){var val=max*g/4,y=c.t+ph-(ph*g/4);s+='<line x1="'+c.l+'" y1="'+y+'" x2="'+(c.w-c.r)+'" y2="'+y+'" stroke="#edf0ed"/><text x="'+(c.l-8)+'" y="'+(y+4)+'" text-anchor="end" fill="#7a877f" font-size="12">'+shortNum(val)+'</text>';}
  var capacityPoints=m.map(function(r,i){return (c.l+(i+.5)*pw/count)+','+(c.t+ph-ph*r.capacity/max);});s+='<polyline points="'+capacityPoints.join(' ')+'" fill="none" stroke="#b86659" stroke-width="1.5" stroke-dasharray="5 5"/><text x="'+(c.w-c.r)+'" y="'+(c.t+14)+'" text-anchor="end" fill="#a75549" font-size="12" font-weight="600">Capacidade definida</text>';
  m.forEach(function(r,i){var x=c.l+(i+.5)*pw/count-bw/2,base=c.t+ph;[['rural','#397552'],['toreton','#c79538'],['hotel','#347e91']].forEach(function(z){var bh=ph*r[z[0]]/max;base-=bh;s+='<rect x="'+x+'" y="'+base+'" width="'+bw+'" height="'+Math.max(0,bh)+'" rx="2" fill="'+z[1]+'"><title>'+lotTypeLabel(z[0])+': '+int(r[z[0]])+'</title></rect>';});s+='<text x="'+(x+bw/2)+'" y="'+Math.max(c.t+15,base-8)+'" text-anchor="middle" fill="#17342a" font-size="13" font-weight="650">'+int(r.total)+'</text><text x="'+(x+bw/2)+'" y="'+(c.h-17)+'" text-anchor="middle" fill="#64736a" font-size="12" font-weight="600">'+r.label+'</text>';});return s+'</svg>';}
function movementBars(m){if(!state.lots.length)return '<div class="chart-empty">As entradas e saídas aparecerão aqui.</div>';var c=chartBase(380),pw=c.w-c.l-c.r,mid=c.t+(c.h-c.t-c.b)/2,ph=(c.h-c.t-c.b)/2,max=Math.max(1,Math.max.apply(null,m.map(function(r){return Math.max(r.entryTotal,r.exitTotal);}))),bw=pw/12*.46,s='<svg viewBox="0 0 '+c.w+' '+c.h+'" role="img" aria-label="Entradas e saídas mensais">';
  for(var g=0;g<=4;g++){var val=max*g/4,offset=(ph-22)*g/4,topY=mid-offset,bottomY=mid+offset;s+='<line x1="'+c.l+'" y1="'+topY+'" x2="'+(c.w-c.r)+'" y2="'+topY+'" stroke="'+(g?'#edf0ed':'#aeb9b1')+'" stroke-width="'+(g?'1':'1.5')+'"/>';if(g){s+='<line x1="'+c.l+'" y1="'+bottomY+'" x2="'+(c.w-c.r)+'" y2="'+bottomY+'" stroke="#edf0ed"/><text x="'+(c.l-9)+'" y="'+(topY+4)+'" text-anchor="end" fill="#718078" font-size="11">'+shortNum(val)+'</text><text x="'+(c.l-9)+'" y="'+(bottomY+4)+'" text-anchor="end" fill="#718078" font-size="11">'+shortNum(val)+'</text>';}else{s+='<text x="'+(c.l-9)+'" y="'+(mid+4)+'" text-anchor="end" fill="#718078" font-size="11">0</text>';}}
  m.forEach(function(r,i){var x=c.l+(i+.5)*pw/12-bw/2,hi=(ph-22)*r.entryTotal/max,ho=(ph-22)*r.exitTotal/max,center=x+bw/2;s+='<rect x="'+x+'" y="'+(mid-hi)+'" width="'+bw+'" height="'+hi+'" rx="3" fill="#397552"><title>Entradas: '+int(r.entryTotal)+'</title></rect><rect x="'+x+'" y="'+mid+'" width="'+bw+'" height="'+ho+'" rx="3" fill="#c79538"><title>Saídas: '+int(r.exitTotal)+'</title></rect>';if(r.entryTotal)s+='<text x="'+center+'" y="'+Math.max(c.t+12,mid-hi-7)+'" text-anchor="middle" fill="#315f47" font-size="11" font-weight="650">'+int(r.entryTotal)+'</text>';if(r.exitTotal)s+='<text x="'+center+'" y="'+Math.min(c.h-c.b-5,mid+ho+14)+'" text-anchor="middle" fill="#8a6118" font-size="11" font-weight="650">'+int(r.exitTotal)+'</text>';s+='<text x="'+center+'" y="'+(c.h-12)+'" text-anchor="middle" fill="#64736a" font-size="12" font-weight="600">'+r.label+'</text>';});s+='<text x="'+c.l+'" y="14" fill="#315f47" font-size="12" font-weight="650">ENTRADAS</text><text x="'+c.l+'" y="'+(c.h-27)+'" fill="#8a6118" font-size="12" font-weight="650">SAÍDAS</text></svg>';return s;}
function cashBars(m,height){if(!state.lots.length)return '<div class="chart-empty">O fluxo aparece quando houver lotes planejados.</div>';var count=m.length||1,dataMax=Math.max(1,Math.max.apply(null,m.map(function(r){return Math.max(r.revenue,r.outflow);}))),step=500000,max=Math.max(step,Math.ceil(dataMax/step)*step),steps=Math.round(max/step),c=chartBase(Math.max(height||260,steps*23+65)),pw=c.w-c.l-c.r,ph=c.h-c.t-c.b,bw=Math.min(64,pw/count*.25),s='<svg viewBox="0 0 '+c.w+' '+c.h+'" role="img" aria-label="Entradas e saídas de dinheiro por mês">';for(var g=0;g<=steps;g++){var val=g*step,y=c.t+ph-ph*val/max,label=val===0?'US$ 0':(val/1000000).toLocaleString('pt-BR',{maximumFractionDigits:1})+' mi';s+='<line x1="'+c.l+'" y1="'+y+'" x2="'+(c.w-c.r)+'" y2="'+y+'" stroke="#e5e9e5"/><text x="'+(c.l-8)+'" y="'+(y+4)+'" text-anchor="end" fill="#65746c" font-size="11">'+label+'</text>';}
  m.forEach(function(r,i){var center=c.l+(i+.5)*pw/count,hi=ph*r.revenue/max,ho=ph*r.outflow/max,inX=center-bw-3,outX=center+3;s+='<rect x="'+inX+'" y="'+(c.t+ph-hi)+'" width="'+bw+'" height="'+hi+'" rx="3" fill="#2e6b45"><title>Entradas: '+usd(r.revenue)+'</title></rect><rect x="'+outX+'" y="'+(c.t+ph-ho)+'" width="'+bw+'" height="'+ho+'" rx="3" fill="#c99a3b"><title>Saídas: '+usd(r.outflow)+'</title></rect><text x="'+center+'" y="'+(c.h-10)+'" text-anchor="middle" fill="#64736a" font-size="13" font-weight="700">'+r.label+'</text>';});return s+'</svg>';}
function cashFlowChart(m,height){if(!state.lots.length)return '<div class="chart-empty">O fluxo aparece quando houver lotes planejados.</div>';var c=chartBase(height||240),pw=c.w-c.l-c.r,ph=c.h-c.t-c.b,count=m.length||1,max=Math.max(1,Math.max.apply(null,m.map(function(r){return Math.max(r.revenue,r.outflow||0);}))),zero=c.t+ph*.54,up=zero-c.t-24,down=c.t+ph-zero-8,bw=Math.min(38,pw/count*.16),s='<svg viewBox="0 0 '+c.w+' '+c.h+'" role="img" aria-label="Entradas e saídas de dinheiro por mês">';s+='<line x1="'+c.l+'" y1="'+zero+'" x2="'+(c.w-c.r)+'" y2="'+zero+'" stroke="#cbd3cd" stroke-width="1.5"/>';
  m.forEach(function(r,i){var outflow=r.outflow||0,center=c.l+(i+.5)*pw/count,inH=up*r.revenue/max,outH=down*outflow/max,inX=center-bw-3,outX=center+3;s+='<rect x="'+inX+'" y="'+(zero-inH)+'" width="'+bw+'" height="'+Math.max(r.revenue?2:0,inH)+'" rx="3" fill="#397552"><title>Entrada: '+usd(r.revenue)+'</title></rect><rect x="'+outX+'" y="'+zero+'" width="'+bw+'" height="'+Math.max(outflow?2:0,outH)+'" rx="3" fill="#c79538"><title>Saída: '+usd(outflow)+'</title></rect>';if(r.revenue)s+='<text x="'+(inX+bw/2)+'" y="'+Math.max(c.t+12,zero-inH-7)+'" text-anchor="middle" fill="#315f47" font-size="12" font-weight="600">'+shortMoney(r.revenue)+'</text>';if(outflow)s+='<text x="'+(outX+bw/2)+'" y="'+Math.min(c.h-c.b-2,zero+outH+14)+'" text-anchor="middle" fill="#8a6118" font-size="12" font-weight="600">'+shortMoney(outflow)+'</text>';s+='<text x="'+center+'" y="'+(c.h-12)+'" text-anchor="middle" fill="#64736a" font-size="12" font-weight="600">'+r.label+'</text>';});return s+'</svg>';}
function shortNum(v){if(v>=1000)return (v/1000).toFixed(v>=10000?0:1)+'k';return Math.round(v);}
function shortMoney(v){if(v>=1000000)return '$'+(v/1000000).toFixed(1)+'M';if(v>=1000)return '$'+Math.round(v/1000)+'k';return '$'+Math.round(v);}

async function importActivePdf(e){
  var f=e.target.files&&e.target.files[0];if(!f)return;showToast('Lendo relatório de lotes ativos...');
  try{
    var pdfjs=window.pdfjsLib;if(!pdfjs)throw new Error('Leitor de PDF não foi carregado.');pdfjs.GlobalWorkerOptions.workerSrc='vendor/pdf.worker.min.js';
    var doc=await pdfjs.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise,parsed=[],bovinoContext={reportDate:'',line:'',hasConsumo:false};
    for(var n=1;n<=doc.numPages;n++){var page=await doc.getPage(n),tc=await page.getTextContent();if(n===1){var header=tc.items.map(function(i){return String(i.str||'').trim();}).join(' ');if(!/Bovino\.OS/i.test(header)||!/Tipo\s+de\s+entrada/i.test(header)||!/kg\/cab\s*\(MS\)/i.test(header))throw new Error('Use o relatório Bovino.OS de Lotes Ativos no novo formato, atualizado em setembro de 2026.');bovinoContext.hasConsumo=false;}parsed=parsed.concat(parseBovinoOsStandardPage(tc.items,bovinoContext));}
    if(!parsed.length)throw new Error('Nenhum lote dos currais A a P foi reconhecido no relatório Bovino.OS.');
    state.lots=state.lots.filter(function(l){return l.source!=='feedmanager';}).concat(parsed);
    state.hasConsumo=!!bovinoContext.hasConsumo;
    save();renderForms();renderAll();go('active');showToast(parsed.length+' lotes importados. Animais próprios são Próprio; Boitel, Parceria e demais tipos são Boitel.');
  }catch(err){console.error(err);showToast(err.message||'Não foi possível ler este relatório PDF.');}finally{e.target.value='';}
}
function parseBovinoOsStandardPage(items,context){
  context=context||{reportDate:'',line:''};
  var clean=items.filter(function(i){return String(i.str||'').trim();}),groups={};
  clean.forEach(function(i){var y=Math.round(i.transform[5]/2)*2;(groups[y]||(groups[y]=[])).push({x:i.transform[4],text:String(i.str).trim()});});
  var ys=Object.keys(groups).map(Number).sort(function(a,b){return b-a;}),reportDate=context.reportDate||'',currentLine=context.line||'',out=[];
  var allText=clean.slice().sort(function(a,b){var yd=b.transform[5]-a.transform[5];return Math.abs(yd)>2?yd:a.transform[4]-b.transform[4];}).map(function(i){return String(i.str).trim();}).join(' ');
  var reportMatch=allText.match(/Data\s+de\s+refer[^:]*:\s*(\d{1,2}\/\d{1,2}\/\d{4})/i);if(reportMatch){reportDate=dateToIso(reportMatch[1]);context.reportDate=reportDate;}
  ys.forEach(function(y){
    var row=groups[y].sort(function(a,b){return a.x-b.x;}),joined=row.map(function(i){return i.text;}).join(' '),lineMatch=joined.match(/Linha:\s*(?:LINHA\s*)?(PASTO|[A-P])\b/i);
    if(lineMatch){currentLine=lineMatch[1].toUpperCase();context.line=currentLine;return;}
    if(currentLine==='PASTO'||/Subtotal\s+LINHA/i.test(joined))return;
    var lotText=textInRange(row,35,88);if(!/^(LOTE|ENFERMARIA)\b/i.test(lotText))return;
    var pen=textInRange(row,88,120).replace(/\s+/g,' ').trim(),qty=parseInt(textInRange(row,120,152).replace(/\D/g,''),10)||0;
    var penLine=(pen.match(/^([A-P])\b/i)||[])[1]||'',rowLine=currentLine||penLine.toUpperCase();
    var deaths=parseInt(textInRange(row,152,178).replace(/\D/g,''),10)||0,breed=textInRange(row,196,236),category=textInRange(row,236,296),rawEntryType=textInRange(row,298,340);
    // A Bovino.OS retirou a coluna "Consumo MN total da baia" a partir de set/2026, o que desloca
    // (para a direita) as colunas seguintes, incluindo D. conf., D. trato, GMD, pesos e datas de saída.
    var hasConsumo=context.hasConsumo!==false,C=reportColumns(hasConsumo);
    var confinementDays=parseInt(textInRange(row,C.days[0],C.days[1]).replace(/\D/g,''),10)||0,entryText=textInRange(row,C.entryDate[0],C.entryDate[1]),entryMatch=entryText.match(/\b\d{1,2}\/\d{1,2}\/\d{4}\b/),entryDate=entryMatch?dateToIso(entryMatch[0]):'';
    if(!entryDate&&reportDate&&confinementDays)entryDate=addDaysToIso(reportDate,1-confinementDays);
    var exitDate=addDaysToIso(entryDate,120),isOwn=entryTypeIsOwn(rawEntryType),type=isOwn?'rural':'hotel';
    if(!qty||!entryDate||!exitDate||!rowLine)return;
    var diet=nearbyDiet(clean,y,!hasConsumo)||'NÃO INFORMADA',treatmentDays=parseInt(textInRange(row,C.treatmentDays[0],C.treatmentDays[1]).replace(/\D/g,''),10)||0;
    var entryWeight=numberBR(textInRange(row,C.entryWeight[0],C.entryWeight[1])),gmd=numberBR(textInRange(row,C.gmd[0],C.gmd[1])),estimatedWeight=numberBR(textInRange(row,C.estimatedWeight[0],C.estimatedWeight[1])),exitWeight=numberBR(textInRange(row,C.exitWeight[0],C.exitWeight[1]));
    var exitEstMatch=textInRange(row,C.estimatedExit[0],C.estimatedExit[1]).match(/\d{1,2}\/\d{1,2}\/\d{4}/),estimatedExit=exitEstMatch?dateToIso(exitEstMatch[0]):'';
    var consumption=C.consumption?numberBR(textInRange(row,C.consumption[0],C.consumption[1])):0,kgCabMS=numberBR(textInRange(row,C.kgCabMS[0],C.kgCabMS[1])),kgCabMN=numberBR(textInRange(row,C.kgCabMN[0],C.kgCabMN[1])),pv=numberBR(textInRange(row,C.pv[0],C.pv[1]));
    var sourceKey=['feedmanager',lotText,pen,entryDate].join('|');out.push({id:uid(type),type:type,name:lotText,origin:isOwn?'Animal próprio':'Boitel',rawCategory:category,rawEntryType:rawEntryType,quantity:qty,entry:entryDate.slice(0,7),exit:exitDate.slice(0,7),entryDate:entryDate,exitDate:exitDate,deaths:deaths,line:rowLine,pen:pen,breed:breed,entryType:isOwn?'Próprio':'Boitel',reportDate:reportDate,diet:diet,days:confinementDays,treatmentDays:treatmentDays,entryWeight:entryWeight,gmd:gmd,estimatedWeight:estimatedWeight,exitWeight:exitWeight,estimatedExit:estimatedExit,consumption:consumption,kgCabMS:kgCabMS,kgCabMN:kgCabMN,pv:pv,source:'feedmanager',sourceKey:sourceKey,notes:'Importado do Bovino.OS; saída calculada em 120 dias após a entrada; linha '+rowLine+', curral '+pen,salePrice:state.defaults.sale,buyPrice:state.defaults.buy,hotelPrice:state.defaults.hotel});
  });return out;
}
function textInRange(row,min,max){return row.filter(function(i){return i.x>=min&&i.x<max;}).map(function(i){return i.text;}).join(' ').trim();}
function dateToIso(v){var p=String(v).split('/'),y=Number(p[2]);if(y<100)y+=2000;return String(y)+'-'+String(Number(p[1])).padStart(2,'0')+'-'+String(Number(p[0])).padStart(2,'0');}

async function importPlanningFiles(e){var files=Array.from(e.target.files||[]);if(!files.length)return;var created=0,skipped=0;for(var f of files){try{var d=JSON.parse(await f.text()),plans=extractPlans(d);plans.forEach(function(p){var farm=p.fazenda||'Fazenda';(p.saidaDist||[]).forEach(function(q,i){q=Math.round(num(q));if(q<=0)return;var mk=labelToKey((p.mesesLabels||[])[i],i,p.startDate);var sourceKey=[farm,p.nome||'',mk,q].join('|');if(state.lots.some(function(l){return l.sourceKey===sourceKey;})){skipped++;return;}var ex=ruralExitFromMonthKey(mk);state.lots.push({id:uid('rural'),type:'rural',name:'Rural · '+farm+' · '+labelKey(mk),origin:farm,quantity:q,entry:mk,exit:ex.exit,entryDate:ex.entryDate,exitDate:ex.exitDate,salePrice:state.defaults.sale,notes:'Importado do Planejamento Rural Pastagem; saída calculada em 120 dias corridos (assumindo entrada no meio do mês informado)',source:'planejamento',sourceKey:sourceKey});created++;});});}catch(err){skipped++;}}
  e.target.value='';save();renderAll();showToast(created?created+' lotes Rural importados.':skipped?'Nenhum lote novo encontrado.':'Arquivo sem saídas planejadas.');if(created)go('rural');}
function extractPlans(d){if(!d)return[];if(d.tipo==='rural_pastagem_plano_confirmado'||(Array.isArray(d.saidaDist)&&Array.isArray(d.mesesLabels)))return[d];var s=d.state||d;if(Array.isArray(s.planosConfirmados)&&s.planosConfirmados.length)return[s.planosConfirmados[s.planosConfirmados.length-1]];if(s.distribuicao&&Array.isArray(s.distribuicao.saida)){var start=s.data||s.dataInicio||keyOf(state.year,0);var p=start.split('-'),labels=Array.from({length:12},function(_,i){var k=addMonths(keyOf(Number(p[0]),Number(p[1])-1),i);return labelKey(k);});return[{fazenda:s.fazenda||d.fazenda||'Fazenda',nome:'Distribuição manual',mesesLabels:labels,saidaDist:s.distribuicao.saida.map(function(x){return num(x);}),startDate:start}];}return[];}
function labelToKey(lbl,i,start){if(lbl){var x=String(lbl).trim().toLowerCase(),parts=x.split('/'),mi=['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'].indexOf((parts[0]||'').slice(0,3));if(mi>=0){var yy=Number(parts[1]);if(yy<100)yy+=2000;return keyOf(yy,mi);}}if(start)return addMonths(String(start).slice(0,7),i);return keyOf(state.year,i);}
function exportBackup(){var payload={tipo:'rural_pastagem_confinamento',suite:'rural_pastagem',modulo:'confinamento',versao:1,exportadoEm:new Date().toISOString(),state:state};download('Rural_Pastagem_Confinamento_'+state.year+'.json',JSON.stringify(payload,null,2),'application/json');showToast('Dados exportados.');}
async function importBackup(e){var f=e.target.files&&e.target.files[0];if(!f)return;try{var d=JSON.parse(await f.text()),s=d.state||d;if(!Array.isArray(s.lots))throw new Error();if(!confirm('Substituir o planejamento atual pelos dados deste arquivo?'))return;state=Object.assign(defaults(),s,{capacity:num(s.capacity)||CAPACITY,capacityByMonth:s.capacityByMonth||{},year:new Date().getFullYear()});save();renderForms();renderAll();showToast('Planejamento importado.');}catch(err){showToast('Este arquivo não é um planejamento de confinamento válido.');}finally{e.target.value='';}}
function download(name,text,type){var b=new Blob([text],{type:type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u);},800);}
function confirmPlan(){var name=prompt('Nome deste plano confirmado:','Plano '+new Date().toLocaleDateString('pt-BR'));if(!name)return;var m=model(),plan={id:uid('plan'),name:name,createdAt:new Date().toISOString(),year:state.year,horizonMonths:horizonMonths(),lots:JSON.parse(JSON.stringify(state.lots)),defaults:Object.assign({},state.defaults),stats:{peak:Math.max.apply(null,m.map(function(r){return r.total;})),toretonBuy:sum(m,function(r){return r.toretonPurchases;}),revenue:sum(m,function(r){return r.revenue;}),net:sum(m,function(r){return r.net;})}};state.plans.push(plan);state.activePlanId=plan.id;save();renderPlans();showToast('Plano confirmado e protegido.');}
function renderPlans(){var box=el('plansList');if(!state.plans.length){box.innerHTML='<div class="empty-state">Nenhum plano confirmado. Confirme uma versão para poder testar outros cenários sem perder esta referência.</div>';return;}box.innerHTML=state.plans.slice().reverse().map(function(p){return '<article class="plan-card '+(state.activePlanId===p.id?'active-plan':'')+'"><span class="section-tag">'+(state.activePlanId===p.id?'PLANO EM USO':'PLANO SALVO')+'</span><h2>'+esc(p.name)+'</h2><div class="plan-meta">'+new Date(p.createdAt).toLocaleString('pt-BR')+' · '+p.year+'</div><div class="plan-stats"><div class="plan-stat"><span>Pico</span><strong>'+int(p.stats.peak)+' cab</strong></div><div class="plan-stat"><span>Compra Toreton</span><strong>'+usd(p.stats.toretonBuy)+'</strong></div><div class="plan-stat"><span>Receita</span><strong>'+usd(p.stats.revenue)+'</strong></div><div class="plan-stat"><span>Saldo</span><strong>'+usd(p.stats.net)+'</strong></div></div><div class="plan-actions"><button class="btn ghost" onclick="RP.loadPlan(\''+p.id+'\')">Abrir plano</button><button class="btn ghost" onclick="RP.exportPlan(\''+p.id+'\')">Exportar</button><button class="btn danger" onclick="RP.deletePlan(\''+p.id+'\')">Excluir</button></div></article>';}).join('');}
function loadPlan(id){var p=state.plans.find(function(x){return x.id===id;});if(!p)return;if(!confirm('Abrir este plano e substituir os lotes que estão na tela agora?'))return;state.year=new Date().getFullYear();state.horizonMonths=Number(p.horizonMonths)===24?24:12;state.lots=JSON.parse(JSON.stringify(p.lots));state.defaults=Object.assign({},p.defaults);state.activePlanId=p.id;save();updateHorizonLabels();renderForms();renderAll();showToast('Plano aberto.');}
function deletePlan(id){if(!confirm('Excluir este plano confirmado?'))return;state.plans=state.plans.filter(function(p){return p.id!==id;});if(state.activePlanId===id)state.activePlanId=null;save();renderPlans();}
function exportPlan(id){var p=state.plans.find(function(x){return x.id===id;});if(!p)return;download('Plano_Confinamento_'+p.year+'_'+p.name.replace(/[^a-z0-9]+/gi,'_')+'.json',JSON.stringify({tipo:'rural_pastagem_confinamento_plano',versao:1,plano:p},null,2),'application/json');}

window.RP={edit:editLot,remove:deleteLot,loadPlan:loadPlan,deletePlan:deletePlan,exportPlan:exportPlan};
document.addEventListener('DOMContentLoaded',init);
})();
